---
title: "All Plotting functions"
output: html_document
editor_options: 
  chunk_output_type: console
---

<!-- Run this 'development' chunk -->
<!-- Store every call to library() that you need to explore your functions -->

```{r development, include=FALSE}
library(testthat)
library(ggplot2)
```

<!--
 You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.

If it is the first time you use {fusen}, after 'description', you can directly run the last chunk of the present file with inflate() inside.
--> 

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```


<!-- 
 Store your dataset in a directory named "inst/" at the root of your project.
 Use it for your tests in this Rmd thanks to `pkgload::load_all()` to make it available
and `system.file()` to read it in your examples.

- There already is a dataset in the "inst/" directory to be used in the examples below
-->

```{r development-dataset}
# Run all this chunk in the console directly
# There already is a dataset in the "inst/" directory
# Make the dataset file available to the current Rmd during development
pkgload::load_all(path = here::here(), export_all = FALSE)

```


# Population type per year

<!--
Create a chunk for the core of the function

- The chunk needs to be named `function` at least
- It contains the code of a documented function
- The chunk can also be named `function-my_median` to make it easily
findable in your Rmd
- Let the `@examples` part empty, and use the next `examples` chunk instead to present reproducible examples

After inflating the template

-  This function code will automatically be added in a new file in the "R/" directory
-->

```{r function-population_type_per_year}
#' Graph of population type per year
#'
#' @param start_year Numeric value of first year  
#' @param country_asylum_iso3c Character value with the ISO-3 character code of the Country of Asylum
#' @param pop_type Vector of character values. Possible population type (e.g.: REF, IDP, ASY, VDA, OOC, STA)
#'
#' @return
#' Population type per year graph
#' @export
#'
#' @examples
population_type_per_year <- function(start_year = 2015,
                                     country_asylum_iso3c = country_asylum_iso3c,
                                     pop_type = Population.type
                                     ) {
  
  cols_poptype <- c("Asylum-seekers" = "#18375F",
                    "Refugees" = "#0072BC",
                    "Venezuelans Displaced Abroad" = "#EF4A60", 
                    "Others of Concern to UNHCR" = "#999999",
                    "Internally Displaced Persons" = "#00B398",
                    "Stateless Persons" = "#E1CC0D")
  
  
  df <- unhcrdatapackage::end_year_population_totals_long  |> 
    dplyr::filter(CountryAsylumCode != "UKN",
                  !is.na(CountryAsylumCode),
                  Year >= start_year,  #### Parameter
                  CountryAsylumCode == country_asylum_iso3c, #### Parameter
                  Population.type %in% pop_type #### Parameter
    )  |>  
    dplyr::group_by(Year, CountryAsylumName, Population.type.label)  |> 
    dplyr::summarise(Value = sum(Value, na.rm = TRUE)) |> 
    dplyr::ungroup()
  
  CountryAsylum_name_text <- df |> 
    dplyr::distinct(CountryAsylumName) |> 
    dplyr::pull()
  
  year_breaks <- diff(range(df$Year)) + 1 
  
  p <- ggplot(df) +
    geom_col(aes(x = Year, y = Value, fill = Population.type.label),
             width = 0.7) +
    geom_text(aes(x = Year, 
                  y = Value, 
                  color = Population.type.label, 
                  label = scales::label_number_si(accuracy = 1)(Value)),
              position = position_stack(vjust = 0.5),
              show.legend = FALSE,
              size = 5) +
    scale_color_manual(values = c("#FFFFFF",
                                  "#FFFFFF",
                                  "#FFFFFF",
                                  "#FFFFFF",
                                  "#FFFFFF",
                                  "#FFFFFF")) +
    scale_fill_manual(values = cols_poptype,
                      drop = TRUE,
                      limits = force) +
    scale_x_continuous(breaks = scales::pretty_breaks(n = year_breaks)) +
    scale_y_continuous(expand = expansion(c(0, 0.1))) +
    labs(title = paste0(CountryAsylum_name_text, ": Population type per year"), 
         subtitle = "Number of people (thousand)",
         caption = "Source: UNHCR Refugee Data Finder") +
    unhcrthemes::theme_unhcr(grid = FALSE, axis = "x",
                             axis_title = FALSE, axis_text = "x") +
    stat_summary(fun = sum, aes(x = Year, y = Value, label = scales::label_number_si(accuracy = 1)(..y..), group = Year), 
                 geom = "text", size = 5,
                 vjust = -0.5) +
    theme(legend.direction = "vertical",
          legend.key.size = unit(0.8, 'cm'),
          text = element_text(size = 20),
          plot.subtitle=element_text(size=19),
          plot.title = element_text(size=23),
          plot.caption = element_text(size=13))
  
  p
  }
```

<!--
Create a chunk with an example of use for your function

- The chunk needs to be named `examples` at least
- It contains working examples of your function
- The chunk is better be named `examples-my_median` to be handled
correctly when inflated as a vignette

After inflating the template

-  This example will automatically be added in the '@examples' part of our function above in the "R/" directory
- This example will automatically be added in the vignette created from this Rmd template
-->

```{r examples-population_type_per_year}
population_type_per_year(start_year = 2010,
                  country_asylum_iso3c = "PAN",
                  pop_type = c("REF", 
                               "ASY", 
                               "VDA", 
                               "OOC",
                               "STA",
                               "IDP"
                               )
                  )
```

<!--
Create a chunk with a test of use for your function

- The chunk needs to be named `tests` at least
- It contains working tests of your function
- The chunk is better be named `tests-my_median` to be handled
correctly when inflated as a vignette

After inflating the template

-  This test code will automatically be added in the "tests/testthat/" directory
-->

```{r tests-population_type_per_year}


```



# Main country of origin - Absolute value


```{r function-main_coo_absolute}
#' Main country of origin - Absolute value
#'
#' @param year Numeric value of the year (eg.: 2020)
#' @param country_asylum_code Character value with the ISO-3 character code of the Country of Asylum
#' @param top_n_countries Numeric value of number of main countries that the graph should display
#' @param pop_type Character value. Possible population type (e.g.: REF, IDP, ASY, VDA, OOC, STA)
#' 
#' @return
#' Main country of origin - Absolute value Graph
#' @export
#'
#' @examples
population_type_abs <- function(year = 2021,
                                country_asylum_iso3c = country_asylum_iso3c,
                                top_n_countries = 9,
                                pop_type = "REF"
                              ) {
  
  cols_poptype <- list(ASY = c("Asylum-seekers", "#18375F"),
                       REF = c("Refugees", "#0072BC"),
                       VDA = c("Venezuelans Displaced Abroad", "#EF4A60"), 
                       OOC = c("Others of Concern to UNHCR", "#999999"),
                       IDP = c("Internally Displaced Persons", "#00B398"),
                       STA = c("Stateless Persons", "#E1CC0D")
  )
  
  
  df <-  
    unhcrdatapackage::end_year_population_totals  |> 
    dplyr::filter(CountryAsylumCode != "UKN",
                  !is.na(CountryAsylumCode),
                  Year == year,  #### Parameter
                  CountryAsylumCode == country_asylum_iso3c, #### Parameter
    )  |>  
    dplyr::select(CountryAsylumName, CountryOriginName,!!sym(pop_type)) |>
    dplyr::group_by(CountryAsylumName, CountryOriginName) |>
    dplyr::filter(!!sym(pop_type) != 0) |>
    dplyr::mutate(pop_type_value = sum(!!sym(pop_type), na.rm=TRUE)) |> 
    dplyr::ungroup() |>
    dplyr::mutate(
      origin_data_prot = forcats::fct_lump_n(
        f = CountryOriginName,
        n = top_n_countries,  #### Parameter
        w = pop_type_value,
        other_level = 'Other nationalities',
        ties.method = "last"
      )
    ) |>
    dplyr::mutate(origin_data_prot = forcats::fct_explicit_na(origin_data_prot,
                                                              'Other nationalities')) |>
    dplyr::group_by(CountryAsylumName,origin_data_prot) |>
    dplyr::summarise(pop_type_value = sum(pop_type_value, na.rm = TRUE)) |>
    dplyr::ungroup() |> 
    dplyr::arrange(desc(pop_type_value)) |>
    dplyr::filter(pop_type_value != 0L) |>
    dplyr::mutate(
      origin_data_prot = forcats::fct_rev(forcats::fct_inorder(origin_data_prot)),
      origin_data_prot =  suppressWarnings(
        dplyr::case_when(
          origin_data_prot == "Other nationalities" ~ forcats::fct_relevel(origin_data_prot,
                                                                           "Other nationalities",
                                                                           after = 0),
          TRUE ~ origin_data_prot
        )
      ),
      perc = scales::percent(
        pop_type_value / sum(pop_type_value),
        accuracy = 1,
        trim = FALSE
      )
    )
  
  CountryAsylum_name_text <- df |> 
    dplyr::distinct(CountryAsylumName) |> 
    dplyr::pull()



p <- 
  ggplot(df) +
  geom_col(aes(x = pop_type_value, y = origin_data_prot),
           fill = cols_poptype[[pop_type]][2],
           width = 0.8) +
  ## Position label differently in the bar in white - outside bar in black
  geom_text(
    data = subset(df, pop_type_value < max(pop_type_value) / 1.5),
    aes(
      x = pop_type_value,
      y = origin_data_prot,
      label = scales::label_number(accuracy = 1,
                                   scale_cut = scales::cut_short_scale())(pop_type_value)
    ),
    hjust = -0.1 ,
    vjust = 0.5,
    colour = "black",
    size = 5
  ) +
  geom_text(
    data = subset(df, pop_type_value >= max(pop_type_value) / 1.5),
    aes(
      x = pop_type_value,
      y = origin_data_prot,
      label = scales::label_number(accuracy = 1,
                                   scale_cut = scales::cut_short_scale())(pop_type_value)
    ),
    hjust = 1.1 ,
    vjust = 0.5,
    colour = "white",
    size = 5
  ) +
  labs(title = paste0(CountryAsylum_name_text, ": Main Countries of origin (", cols_poptype[[pop_type]][1], ")", " | ",  year),
       subtitle = "Number of people",
       caption = "Source: UNHCR Refugee Data Finder\n© UNHCR, The UN Refugee Agency") +
  scale_x_continuous(expand = expansion(c(0, 0.1))) +
  unhcrthemes::theme_unhcr(grid = FALSE, axis = "y", axis_title = FALSE, axis_text = "y") +
  theme(legend.direction = "vertical",
        legend.key.size = unit(0.8, 'cm'),
        text = element_text(size = 20),
        plot.subtitle=element_text(size=19),
        plot.title = element_text(size=23),
        plot.caption = element_text(size=13))
 p
  }
```

```{r examples-main_coo_absolute}
population_type_abs(year = 2020,
                    country_asylum_iso3c = "USA",
                    top_n_countries = 4,
                    pop_type = "REF"
                    ) 
```

```{r tests-main_coo_absolute}

```



# Main country of origin - Percentage


```{r function-main_coo_percentage}
#' Main country of origin - Percentage
#'
#' @param year Numeric value of the year (eg.: 2020)
#' @param country_asylum_code Character value with the ISO-3 character code of the Country of Asylum
#' @param top_n_countries Numeric value of number of main countries that the graph should display
#' @param pop_type Character value. Possible population type (e.g.: REF, IDP, ASY, VDA, OOC, STA)
#' 
#' @return
#' Main country of origin - Percentage Graph
#' @export
#'
#' @examples
population_type_perc <- function(year = 2021,
                                country_asylum_iso3c = country_asylum_iso3c,
                                top_n_countries = 9,
                                pop_type = "REF"
                              ) {
  
  cols_poptype <- list(ASY = c("Asylum-seekers", "#18375F"),
                       REF = c("Refugees", "#0072BC"),
                       VDA = c("Venezuelans Displaced Abroad", "#EF4A60"), 
                       OOC = c("Others of Concern to UNHCR", "#999999"),
                       IDP = c("Internally Displaced Persons", "#00B398"),
                       STA = c("Stateless Persons", "#E1CC0D")
  )
  
  
  df <-  
    unhcrdatapackage::end_year_population_totals  |> 
    dplyr::filter(CountryAsylumCode != "UKN",
                  !is.na(CountryAsylumCode),
                  Year == year,  #### Parameter
                  CountryAsylumCode == country_asylum_iso3c, #### Parameter
    )  |>  
    dplyr::select(CountryAsylumName, CountryOriginName,!!sym(pop_type)) |>
    dplyr::group_by(CountryAsylumName, CountryOriginName) |>
    dplyr::filter(!!sym(pop_type) != 0) |>
    dplyr::mutate(pop_type_value = sum(!!sym(pop_type), na.rm=TRUE)) |> 
    dplyr::ungroup() |>
    dplyr::mutate(
      origin_data_prot = forcats::fct_lump_n(
        f = CountryOriginName,
        n = top_n_countries,  #### Parameter
        w = pop_type_value,
        other_level = 'Other nationalities',
        ties.method = "last"
      )
    ) |>
    dplyr::mutate(origin_data_prot = forcats::fct_explicit_na(origin_data_prot,
                                                              'Other nationalities')) |>
    dplyr::group_by(CountryAsylumName,origin_data_prot) |>
    dplyr::summarise(pop_type_value = sum(pop_type_value, na.rm = TRUE)) |>
    dplyr::ungroup() |> 
    dplyr::arrange(desc(pop_type_value)) |>
    dplyr::filter(pop_type_value != 0L) |>
    dplyr::mutate(
      origin_data_prot = forcats::fct_rev(forcats::fct_inorder(origin_data_prot)),
      origin_data_prot =  suppressWarnings(
        dplyr::case_when(
          origin_data_prot == "Other nationalities" ~ forcats::fct_relevel(origin_data_prot,
                                                                           "Other nationalities",
                                                                           after = 0),
          TRUE ~ origin_data_prot
        )
      ),
      perc = scales::percent(
        pop_type_value / sum(pop_type_value),
        accuracy = 1,
        trim = FALSE
      )
    )
  
  CountryAsylum_name_text <- df |> 
    dplyr::distinct(CountryAsylumName) |> 
    dplyr::pull()



p <- 
  ggplot(df) +
  geom_col(aes(x = pop_type_value, y = origin_data_prot),
           fill = cols_poptype[[pop_type]][2],
           width = 0.8) +
  ## Position label differently in the bar in white - outside bar in black
  geom_text(
    data = subset(df, pop_type_value < max(pop_type_value) / 1.5),
    aes(
      x = pop_type_value,
      y = origin_data_prot,
      label = perc
    ),
    hjust = -0.1 ,
    vjust = 0.5,
    colour = "black",
    size = 5
  ) +
  geom_text(
    data = subset(df, pop_type_value >= max(pop_type_value) / 1.5),
    aes(
      x = pop_type_value,
      y = origin_data_prot,
      label = perc
    ),
    hjust = 1.1 ,
    vjust = 0.5,
    colour = "white",
    size = 5
  ) +
  labs(title = paste0(CountryAsylum_name_text, ": Main Countries of origin (", cols_poptype[[pop_type]][1], ")", " | ",  year),
       subtitle = "Percentage",
       caption = "Source: UNHCR Refugee Data Finder\n© UNHCR, The UN Refugee Agency") +
  scale_x_continuous(expand = expansion(c(0, 0.1))) +
  unhcrthemes::theme_unhcr(grid = FALSE, axis = "y", axis_title = FALSE, axis_text = "y") +
  theme(legend.direction = "vertical",
        legend.key.size = unit(0.8, 'cm'),
        text = element_text(size = 20),
        plot.subtitle=element_text(size=19),
        plot.title = element_text(size=23),
        plot.caption = element_text(size=13))
 p
  }
```

```{r examples-main_coo_percentage}
population_type_perc(year = 2021,
                    country_asylum_iso3c = "BRA",
                    top_n_countries = 9,
                    pop_type = "REF"
                    ) 
```

```{r tests-main_coo_percentage}

```


# Increases and Decreases in Population Groups


```{r function-diff_in_pop_groups}
#' Increases and Decreases in Population Groups
#'
#' @param year Numeric value of the year (eg.: 2020)
#' @param country_asylum_code Character value with the ISO-3 character code of the Country of Asylum
#' @param pop_type Vector of character values. Possible population type (e.g.: REF, IDP, ASY, VDA, OOC, STA)
#' 
#' @return
#' Increases and Decreases in Population Groups Graph
#' @export
#'
#' @examples
diff_pop <- function(year = 2021,
                     country_asylum_iso3c = country_asylum_iso3c,
                     pop_type = pop_type
) {
  
  diff_perc <- function(x){
    x = as.numeric((x - dplyr::lag(x))/dplyr::lag(x)) + 0
    
  }
  
  
  df <- unhcrdatapackage::end_year_population_totals  |> 
    dplyr::filter(CountryAsylumCode != "UKN",
                  !is.na(CountryAsylumCode),
                  (Year == year-1 | Year == year),  #### Parameter
                  CountryAsylumCode == country_asylum_iso3c #### Parameter
    ) |> 
    dplyr::group_by(Year, CountryAsylumName) |> 
    dplyr::summarise(dplyr::across(where(is.numeric), sum)) |> 
    dplyr::ungroup() |> 
    dplyr::arrange(Year) |> 
    dplyr::select(-c(Year)) |> 
    dplyr::group_by(CountryAsylumName) |> 
    dplyr::summarise(dplyr::across(where(is.numeric), 
                                   list(diffabs = diff,
                                        diffperc = diff_perc),
                                   .names = "{.col}_{.fn}")) |> 
    dplyr::ungroup() |> 
    dplyr::slice(2) 
  
  df <- replace(df, is.na(df), 0)
  
  df <- df |> 
    tidyr::gather(v, value, REF_diffabs:VDA_diffperc) |> 
    tidyr::separate(v, c("pop_type", "value_type"), sep = "\\_") |> 
    tidyr::spread(key = value_type, value = value) |> 
    dplyr::mutate(diffper =scales::percent(
      diffperc,
      accuracy = 1,
      trim = FALSE
    ))
  
  
  p <- df |> 
    dplyr::filter(pop_type %in% pop_type) |>
    ggplot() +
    geom_col(aes(x = pop_type, 
                 y = diffabs,
                 fill = pop_type),
             width = 0.8) +
    scale_fill_manual(
      values = c("ASY" = "#18375F",
                 "REF" = "#0072BC",
                 "VDA" = "#EF4A60", 
                 "OOC" = "#999999",
                 "IDP" = "#00B398",
                 "STA" = "#E1CC0D"),
      drop= TRUE,
      limits = force,
      guide="none"
    ) +
    scale_x_discrete(labels= c("ASY" = "Asylum-seekers",
                               "REF" = "Refugees",
                               "VDA" = "Venezuelans Displaced\nAbroad", 
                               "OOC" = "Others of Concern\nto UNHCR",
                               "IDP" = "Internally Displaced\nPersons",
                               "STA" = "Stateless Persons"),
                     drop = TRUE,
                     limits = force) +
    geom_text(
      data = subset(df, diffabs >= 0 & diffabs < max(diffabs) / 1.5),
      aes(
        x = pop_type,
        y = diffabs,
        label = scales::label_number(accuracy = 1,
                                     scale_cut = scales::cut_short_scale())(diffabs)
      ),
      vjust = -0.5 ,
      colour = "black",
      size = 5
    ) +
    geom_text(
      data = subset(df, diffabs >= 0 & diffabs < max(diffabs) / 1.5),
      aes(
        x = pop_type,
        y = diffabs,
        label = diffper
      ),
      vjust = -2.0 ,
      colour = "black",
      size = 5
    ) +
    geom_text(
      data = subset(df, diffabs >= 0 & diffabs >= max(diffabs) / 1.5),
      aes(
        x = pop_type,
        y = diffabs,
        label = scales::label_number(accuracy = 1,
                                     scale_cut = scales::cut_short_scale())(diffabs)
      ),
      vjust = 2.7 ,
      colour = "white",
      size = 5
    ) + 
    geom_text(
      data = subset(df, diffabs >= 0 & diffabs >= max(diffabs) / 1.5),
      aes(
        x = pop_type,
        y = diffabs,
        label = diffper
      ),
      vjust = 1.2 ,
      colour = "white",
      size = 5
    ) + #################################
  # geom_text(
  #   data = subset(df, diffabs < 0 & diffabs <= min(diffabs) / 1.5),
  #   aes(
  #     x = pop_type,
  #     y = diffabs,
  #     label = scales::label_number(accuracy = 1,
  #                                  scale_cut = scales::cut_short_scale())(diffabs)
  #   ),
  #   vjust = -2.0 ,
  #   colour = "white",
  #   size = 5
  # )  +
  #   geom_text(
  #     data = subset(df, diffabs < 0 & diffabs <= min(diffabs) / 1.5),
  #     aes(
  #       x = pop_type,
  #       y = diffabs,
  #       label = diffper
  #     ),
  #     vjust = -0.5 ,
  #     colour = "white",
  #     size = 5
  #   ) +
  geom_text(
    data = subset(df, diffabs < 0/ 1.5),
    aes(
      x = pop_type,
      y = diffabs,
      label = scales::label_number(accuracy = 1,
                                   scale_cut = scales::cut_short_scale())(diffabs)
    ),
    vjust =  1.2,
    colour = "black",
    size = 5
  ) + 
    geom_text(
      data = subset(df, diffabs < 0  / 1.5),
      aes(
        x = pop_type,
        y = diffabs,
        label = diffper
      ),
      vjust = 2.7,
      colour = "black",
      size = 5
    ) +
    geom_hline(yintercept = 0, color = "black") +
    labs(title = paste0(df |> 
                          dplyr::distinct(CountryAsylumName) |> 
                          dplyr::pull(), 
                        ": Increases and Decreases in Population Groups | ",
                        year-1,
                        "-",
                        year),
         subtitle = "Number of people and percentage",
         caption = "Source: UNHCR Refugee Data Finder\n© UNHCR, The UN Refugee Agency")  + 
    unhcrthemes::theme_unhcr(grid = FALSE, axis = "x", axis_title = FALSE, axis_text = "x") +
    theme(axis.line.x = element_line(color="white"),
          axis.text.x = element_text(size=10))
  
  p
}
```

```{r examples-diff_in_pop_groups}
diff_pop(year = 2021,
         country_asylum_iso3c = "USA",
         pop_type = c("REF", "ASY")
         )

```

```{r tests-diff_in_pop_groups}

```







<!--
# There can be development actions

Create a chunk with 'development' actions

- The chunk needs to be named `development` or `dev`
- It contains functions that are used for package development only
- Note that you may want to store most of these functions in the 0-dev_history.Rmd file

These are only included in the present flat template file, their content will not be part of the package anywhere else.
-->

```{r development-inflate, eval=FALSE}
# Keep eval=FALSE to avoid infinite loop in case you hit the knit button
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_full.Rmd", vignette_name = "Get started")
```

