# WARNING - Generated by {fusen} from dev/dev_plot_Country.Rmd: do not edit by hand # nolint: line_length_linter.

# test_that("plot_ctr_keyfig works", {  expect_true(inherits(plot_ctr_keyfig, "function")) })
