# WARNING - Generated by {fusen} from dev/dev_plot_Region.Rmd: do not edit by hand # nolint: line_length_linter.

# test_that("plot_reg_population_type_abs works", {   expect_true(inherits(plot_reg_population_type_abs, "function")) })
