# WARNING - Generated by {fusen} from /dev/dev_golem_module.Rmd: do not edit by hand

#' A small function to add a prefix slash
#' @noRd
#' @keywords internal
#' @return path
#' @param path file path
add_slashes <- function(path) {
  if (length(path) && !grepl("^/", path)) {
    path <- paste0("/", path)
  }
  path
}
