# WARNING - Generated by {fusen} from /dev/dev_template.Rmd: do not edit by hand

#' Tcheck_font 
#' 
#' verify that FontAwesome6Free-Solid is actually available
#' 
#' @return nada
#' @noRd 
#' @keywords internal
#' 
#' @importFrom dplyr  desc select  case_when lag mutate group_by filter summarise ungroup
#'               pull distinct n arrange across slice left_join
#' @importFrom extrafont fonttable font_import
#' @importFrom sysfonts font_add
#' @importFrom utils download.file
#' @export
#' @examples
#' check_font()
check_font <- function(){
  
      ## FontAwesome6  includes humanitarian icon... 
    fontcheck <- extrafont::fonttable() |>
              dplyr::as_tibble() |>
              dplyr::filter(grepl("Awesom", FamilyName)) 

    if( ! ("FontAwesome6Free-Solid" %in% fontcheck$FontName) ) {
      fa_font <- here::here("",  "fa-solid-900-6.ttf")
      download.file("https://raw.githubusercontent.com/FortAwesome/Font-Awesome/6.x/webfonts/fa-solid-900.ttf",
                    destfile = fa_font, method = "curl")
      extrafont::font_import(paths = dirname(fa_font), prompt = FALSE)
      sysfonts::font_add(family =  "Font Awesome 6 Free Solid", regular = fa_font)
    } else {
    
    sysfonts::font_add(family = "Font Awesome 6 Free Solid" , 
                       regular = as.character(fontcheck |> 
                                                dplyr::filter( FamilyName == "Font Awesome 6 Free Solid") |>
                                                dplyr::pull(fontfile)) )
    }
    
}
