# WARNING - Generated by {fusen} from dev/dev_plot_Region.Rmd: do not edit by hand # nolint: line_length_linter.

# --- Standard Constants for UNHCR Style ---
# Defined to match dev_plot_Country
dict_pop_type_label <- c(
    "refugees" = "REF",
    "returned_refugees" = "RETURNED_REF",
    "asylum_seekers" = "ASY",
    "idps" = "IDP",
    "returned_idps" = "RETURNED_IDP",
    "oip" = "OIP",
    "stateless" = "STA",
    "ooc" = "OOC",
    "hst" = "HST"
)

cols_poptype <- c(
    "Refugees" = "#0072BC",
    "Asylum-seekers" = "#6CD8FD",
    "Internally displaced\npersons" = "#32C189",
    "Other people in need\nof international protection" = "#D25A45",
    "Stateless people" = "#FFC740",
    "Others of concern\nto UNHCR" = "#A097E3",
    "Host community" = "#BFBFBF",
    "Returned refugees" = "#00B398",
    "Returned idps" = "#00B398",
    "Other" = "#BFBFBF"
)

# For plots that use abbreviations keys
cols_poptype_abbr <- c(
    "REF" = "#0072BC",
    "ASY" = "#6CD8FD",
    "IDP" = "#32C189",
    "OIP" = "#D25A45",
    "STA" = "#FFC740",
    "OOC" = "#A097E3",
    "HST" = "#BFBFBF",
    "HCO" = "#BFBFBF"
)
