# WARNING - Generated by {fusen} from /dev/dev_golem_module.Rmd: do not edit by hand

#' annotate UI Function
#'
#' @description A shiny Module to lauch the annotatation gadget for a chart
#'
#' @param id,annotate,output,session Internal parameters for {shiny}.
#'
#' @noRd 
#'
#' @importFrom shiny NS tagList 
mod_annotate_ui <- function(id){
  ns <- NS(id)
  tagList(

     # actionButton("overlay_annotate",
     #               label = "Overlay an interpretation annotation!  -- not working yet",
     #               icon = icon("hand-point-up"),
     #               onclick = "" ) 
  )
}
    
#' annotate Server Functions
#'
#' @noRd 
mod_annotate_server <- function(id, chart){
  moduleServer( id, function(input, output, session){
    ns <- session$ns
    #annotate_gadget(chart = thischart)

    
 
  })
}
    
## To be copied in the UI
# mod_annotate_ui("annotate_1")
    
## To be copied in the server
# mod_annotate_server("annotate_1")

