# WARNING - Generated by {fusen} from /dev/dev_golem_module.Rmd: do not edit by hand

#' demographics UI Function
#'
#' @description A shiny Module.
#'
#' @param id,input,output,session Internal parameters for {shiny}.
#'
#' @noRd 
#'
#' @importFrom shiny NS tagList 
mod_demographics_ui <- function(id){
  ns <- NS(id)
  tagList( 
        plotOutput(ns("plot_ctr_pyramid"))
  )
}
    
#' demographics Server Functions
#'
#' @noRd 
mod_demographics_server <- function(id, reactiveParameters){
  moduleServer( id, function(input, output, session){
    ns <- session$ns 
        output$plot_ctr_pyramid <- renderPlot({
                        plot_ctr_pyramid(
              year = as.numeric(reactiveParameters$year),
              country_asylum_iso3c = reactiveParameters$country,
              pop_type = c(  "REF"))
                             })
 
  })
}
    
## To be copied in the UI
# mod_demographics_ui("demographics_1")
    
## To be copied in the server
# mod_demographics_server("demographics_1")

