# WARNING - Generated by {fusen} from /dev/dev_golem_module.Rmd: do not edit by hand

#' Landing page UI Function
#'
#' @description A shiny Module.
#'
#' @param id,input,output,session Internal parameters for {shiny}.
#'
#' @noRd 
#' @keywords internal
#' @importFrom shinydashboardPlus carousel carouselItem
#' @importFrom shiny NS tagList 
mod_home_ui <- function(id){
  ns <- NS(id)
  tagList( 

             )
}
                  
                  #, #Doing so, users will: 
                            #  tags$ul(
                            #     tags$li("enhance basic data literacy"), 
                            #     tags$li("further explore data through different filters"), 
                            #     tags$li("be able to create persuasive data stories ") 
                            # )   
                                    # "This app allows Information Managers, Data Analyst and Data Journalist to quickly build data stories on Forced Displacement: Adjust the message in the title, highlight insights in the subtitle, overlay annotation to ease interpretation and filter the data",
                  
                  # for data story telling 

                    # p(HTML("  1. How the different <a href='#shiny-tab-categories'>Categories</a> of Population of concern to UNHCR are evolving over time?")), 
                    # p(HTML("  2. What are the main countries of Origin of Forced Displacement across Borders?")),  
                    # p(HTML("  3. What are the main countries of Destination of Asylum of Forced Displacement across Borders?")),
                    # p(HTML("  4. What are the Demographics profiles of Forcibly Displaced People in relation with the host population?")),
                    # p(HTML("  5. Is the asylum Processing capacity in relation with the demand?")),
                    # p(HTML("  6. What are the trends in terms of Solutions?")),
                    # p(HTML("  7. What is the share of Forcibly Displaced People among total Migrants?")) ,
                  #,
                 # br(),
                  # p ('This app conveniently bring together a series of predefined plots in order to improve data literacy and facilitate the creation of',
                  # tags$a(href="https://edouard-legoupil.github.io/unhcrdatapackage/tuto/tutorial.html", "persuasive data stories") ,
                  # '. Each plot is created through a function that provides a recipe that creates a re-usable chart in line with a',
                  # tags$a(href="https://www.columnfivemedia.com/divisible-content-strategy-gives-brand-less/", "Divisible Content Strategy"),
                  # '. You may',
                  # tags$a(href="https://edouard-legoupil.github.io/unhcrdatapackage/articles/library.html", "enhance the charts story-telling ability"),
                  # ' by adjusting the message in the title, highlighting specific parts of the data or adding annotation to ease interpretation or provide more contextual background.')



#' input Server Functions
#'
#' @noRd 
#' @keywords internal
mod_home_server <- function(id){
  moduleServer( id, function(input, output, session){
    ns <- session$ns
    ## used to get a link to the tabs...

  

  })
}
    
## To be copied in the UI
# mod_home_ui("home_1")
    
## To be copied in the server
# mod_home_server("home_1")

