# WARNING - Generated by {fusen} from /dev/dev_golem_module.Rmd: do not edit by hand

#' processing UI Function
#'
#' @description A shiny Module.
#'
#' @param id,input,output,session Internal parameters for {shiny}.
#'
#' @noRd 
#'
#' @importFrom shiny NS tagList 
#' @keywords internal
mod_processing_ui <- function(id){
  ns <- NS(id)
  tagList(
   tabsetPanel(type = "tabs",
         tabPanel(title= "Decision Flow",
                  mod_plotviz_ui(ns("processing1"),
                  thisPlot = "plot_ctr_process" ) ),
         
         tabPanel(title= "Recognition",
                  mod_plotviz_ui(ns("processing2"), 
                  thisPlot = "plot_ctr_recognition" ) ),
         
         tabPanel(title= "Processing Time",
                  mod_plotviz_ui(ns("processing3"), 
                  thisPlot = "plot_ctr_processing_time" ) )
      ) ## End Tabset
  )
}
    
#' processing Server Functions
#' @param reactiveParameters  Main app filters defined through mod_input
#'
#' @noRd 
#' @import ggplot2
#' @import shiny
#' @keywords internal
mod_processing_server <- function(id, reactiveParameters){
  moduleServer( id, function(input, output, session){
    ns <- session$ns
       mod_plotviz_server("processing1", thisPlot = "plot_ctr_process", reactiveParameters )
       mod_plotviz_server("processing2", thisPlot = "plot_ctr_recognition", reactiveParameters )
       mod_plotviz_server("processing3", thisPlot = "plot_ctr_processing_time", reactiveParameters )
 
  })
}
    
## To be copied in the UI
# mod_processing_ui("processing_1")
    
## To be copied in the server
# mod_processing_server("processing_1")

