# WARNING - Generated by {fusen} from /dev/dev_golem_module.Rmd: do not edit by hand

#' destination UI Function
#'
#' @description A shiny Module.
#'
#' @param id,input,output,session Internal parameters for {shiny}.
#'
#' @noRd 
#'
#' @importFrom shiny NS tagList 
mod_destination_ui <- function(id){
  ns <- NS(id)
  tagList(
            plotOutput(ns("plot_ctr_destination")),
       fluidRow(
        shinydashboard::box( title = "Tell Your Story!",
                              status = "info", 
                              solidHeader = TRUE, 
                              collapsible = TRUE,
                              #background = "light-blue",
                              width = 12, 
                             fluidRow( 
                            column( 6, 
            textInput( inputId =ns( "title"),
                   label ="Your message (max 80 Char)",
                   value=""),
            textInput( inputId = ns( "subtitle"),
                       label ="Add Insights",
                       value="") ),
                            column( 6, 
            checkboxGroupInput(  inputId = ns("pop_type"),
                        label = "What Population Type to include",
                        choices = c(   "Refugee" ="REF", 
                                     "Asylum Seeker"= "ASY", 
                                      "Other in Need of International Protection"="OIP"  ),
                        selected = c(  "ASY"  ) ))
                             )  ) )
  )
}
    
#' destination Server Functions
#'
#' @noRd 
mod_destination_server <- function(id, reactiveParameters){
  moduleServer( id, function(input, output, session){
    ns <- session$ns
    output$plot_ctr_destination <- renderPlot({
              p <-          plot_ctr_destination(
              year = as.numeric(reactiveParameters$year),
              country_origin_iso3c = reactiveParameters$country,
                     pop_type =   input$pop_type)
      
   if (input$title != "") { p<- p + labs(title = input$title)}
   if (input$subtitle != "") { p <- p + labs(subtitle = input$subtitle)}
      
      p
                             })
 
  })
}
    
## To be copied in the UI
# mod_destination_ui("destination_1")
    
## To be copied in the server
# mod_destination_server("destination_1")

