# WARNING - Generated by {fusen} from /dev/dev_golem_module.Rmd: do not edit by hand

#' plotviz UI Function
#'
#' @description A shiny Module.
#'
#' @param id,input,output,session Internal parameters for {shiny}.
#' @param thisPlot identify which plot to output from the library
#'   # 1. Category 
#'    # ## Key Figures
#'    "plot_ctr_keyfig", # year, country_asylum_iso3 
#'    # ## Plot Tree Map of Categories
#'    "plot_ctr_treemap", # year,  country_asylum_iso3c,   pop_type 
#'    # ## Plot Population type per year
#'    "plot_ctr_population_type_per_year", # year,   country_asylum_iso3c, lag,  pop_type  
#'    
#'    # # 2. Origin
#'    # ## Plot Main country of origin  in one specific country - Absolute value
#'    "plot_ctr_population_type_abs", # year , country_asylum_iso3c, top_n_countries,  pop_type = pop_filter, show_diff_label = FALSE   
#'    # ## Plot Main country of origin in one specific country - Percentage
#'    "plot_ctr_population_type_perc", # year , country_asylum_iso3c , top_n_countries, pop_type = "REF"- pop_filter    
#'    # ## Plot Increases and Decreases in Population Groups
#'    "plot_ctr_diff_in_pop_groups", # year,  country_asylum_iso3c,  pop_type  
#'    # ## Plot Origin History
#'    "plot_ctr_origin_history", # year , country_asylum_iso3c ,lag, ,   pop_type , otherprop 
#'   
#'    # # 3. Destination 
#'    # ## Plot Main Destination from  one specific country 
#'    "plot_ctr_destination", # year , country_origin_iso3c, pop_type   
#'    # ## plot recognition rate for a nationality
#'    "plot_ctr_origin_recognition", # year, country_origin_iso3c,  top_n_countries,  measure ,  order_by  
#'     
#'    # # 4. Profile
#'    # ## Plot Age Pyramid
#'    "plot_ctr_pyramid", # year , country_asylum_iso3c , pop_type  
#'    # ## Plot locations within countries
#'    "plot_ctr_location", # year , country_asylum_iso3c, pop_type 
#' 
#'    # # 5. Processing
#'    # ## Plot Refugee Recognition rate in Country
#'    "plot_ctr_recognition", # year,  country_asylum_iso3c, top_n_countries , measure , order_by  
#'    # ## Asylum Applications & Decision over time
#'    "plot_ctr_asylum", # year  country_asylum_iso3c,   lag 
#'    # ## Asylum Processing
#'    "plot_ctr_process", # year,   country_asylum_iso3c ,  otherprop 
#'    # ## Average Asylum Processing Time
#'    "plot_ctr_processing_time", # year =, country_asylum_iso3c ,  country_origin_iso3c ,  procedureType  
#'    
#'    # # 6. Solutions 
#'    # ## Plot Solution Over time 
#'    "plot_ctr_solution", # year , country_asylum_iso3c, pop_type  
#' 
#'    # # 7.Migrant 
#'    # ## Plot Ratio Refugee Migrant 
#'    "plot_ctr_disp_migrant" # year , country_asylum_iso3c ,   
#'
#' @noRd 
#'
#' @importFrom shiny NS tagList 
#' @keywords internal
mod_plotviz_ui <- function(id, thisPlot){
  ns <- NS(id)
  #browser()
  tagList(
      ## Display the plot
        plotOutput(ns("thisplot")),
        browser(),
      ## Display the interface parameters...
       fluidRow(
         shinydashboard::box(
           title = "Tell Your Story!",
           status = "info",
           solidHeader = TRUE,
           collapsible = TRUE,
           #background = "light-blue",
           width = 12,
           fluidRow(
             
             ## First column used to storytelling
             column(
               6,
               textInput(
                 inputId = ns("title"),
                 label = "Title - Highlight your main message! Keep it short!",
                 value = "",
                 placeholder = "Keep it short!"
               ),
               textInput(
                 inputId = ns("subtitle"),
                 label = "SubTitle - Add Insights!",
                 value = "",
                 placeholder = "Help in reading the chart"
               )
             ),
             
             ## Second Columns used for chart parameters..
             column(4, 
               ## pop_type or pop_filter    
               if (thisPlot %in% c( "plot_ctr_treemap",
                                     "plot_ctr_population_type_per_year",
                                     "plot_ctr_diff_in_pop_groups",
                                     "plot_ctr_origin_history",
                                     "plot_ctr_destination")  
                    ){  checkboxGroupInput(  inputId = ns("pop_type"),
                          label = "Population Types to include",
                          choices = c("Refugee" ="REF", 
                                    "Asylum Seeker"= "ASY", 
                                    "Other in Need of International Protection"="OIP" ,
                                    "Other of Concern"= "OOC",
                                    "Stateless"="STA",
                                    "Internally Displaced Persons"=     "IDP" ),
                          selected = c("REF",  "ASY",  "OIP",  "OOC",  "STA",  "IDP" ) )
                 
                    } else if (thisPlot %in% c( "plot_ctr_population_type_abs" ,
                                                  "plot_ctr_population_type_perc") 
                     ){ selectInput(  inputId = ns("pop_type"),
                          label = "Population Type to include",
                          choices = c(   "Refugee" ="REF", 
                                     "Asylum Seeker"= "ASY", 
                                      "Other in Need of International Protection"="OIP"  ),
                          selected =   "ASY" )
                    } else {""},
               
               ## top_n_countries ,  numericInput
               if (thisPlot %in% c( "plot_ctr_population_type_abs",
                                    "plot_ctr_population_type_perc",
                                    "plot_ctr_origin_recognition",
                                    "plot_ctr_recognition")  
                   ){  numericInput( inputId =   ns("top_n_countries"), 
                                label = "Top n countries", 
                                value = 5,  min = 4 , max = 30, step = 1 ,
                                width = '100%') } else {""},
             
               ## lag  # numericInput
               if (thisPlot %in% c("plot_ctr_population_type_per_year",
                                    "plot_ctr_origin_history",
                                    "plot_ctr_asylum")  
                   ){  numericInput( inputId =   ns("lag"), 
                                label = "Lag in years", 
                                value = 3,  min = 3 , max = 10, step = 1 ,
                                width = '100%') } else {""},
             
               ## otherprop   ## numeric input
               if (thisPlot %in% c("plot_ctr_origin_history",
                                    "plot_ctr_process")  
                   ){  numericInput( inputId =   ns("otherprop"), 
                                label = "Percent  to bind as Other", 
                                value = 0.15,  min = 0.05 , max = 0.40, step = 0.05 ,
                                width = '100%') } else {""},
             
             ## show_diff_label  ## boolean
             ## country_origin_iso3c  ## selectise
             ## procedureType ## slectone
             ##   measure ,  selectOne and  order_by  , selectOne
                    ""),
             
             ## Last column used for the two buttons - download chart and reproducibility
             column(
               2,
               downloadButton(
                 outputId =  ns("dl"),
                 label = "Share your story",
                 class = "btn-success" ,
                 icon = shiny::icon("share-from-square")
               )
             )  # End column
           )  # End First Fluid Row...
         ) #  shinydashboard::box
         
       ## Now render the plot... 
       # shinydashboard::box(
       #   width = 12,
       #   plotOutput(ns("thisplot"),
       #               click="annotate_point",
       #               brush= shiny::brushOpts(id="annotate_box"))
       #    ) ## end box
       
       
       ) ## End Main fluid row
  )
}
    
#' plotviz Server Functions
#'
#' @param thisPlot reference to the plot  function from the chart library
#' @param reactiveParameters  Main app filters defined through mod_input
#' @noRd 
#' @import ggplot2
#' @import shiny
#' @keywords internal
mod_plotviz_server <- function(id, thisPlot, reactiveParameters){

  moduleServer( id, function(input, output, session){
    ns <- session$ns 
     # Initialize reactive values
     reactLocal <- reactiveValues(x = 0, y = 0,
                              xmax = 0,  ymax = 0,  xmin = 0,  ymin = 0,
                              xbox = 0,   ybox = 0,  arrowcurve = 0.3,  arrowangle = 140,
                              annot = " ", xcentroid = 0,  ycentroid = 0,
                              thisPlot = "",
                              chart =   ggplot2::ggplot(iris), 
                              code = " # pak::pkg_install(\"edouard-legoupil/unhcrdatapackage\")" ,
                              syntax = " # pak::pkg_install(\"edouard-legoupil/unhcrdatapackage\")" )
    
    
    ### Plot rendering function
    output$thisplot <- renderPlot({
       
    ## Rendering plot Based on type...
    
    # 1. Category 
    # ## Key Figures
      if( thisPlot == "plot_ctr_keyfig"){
        p <-  plot_ctr_keyfig(
                year = as.numeric(reactiveParameters$year),
                country_asylum_iso3c = reactiveParameters$country)
    # ## Plot Tree Map of Categories
      } else  if( thisPlot == "plot_ctr_treemap"){
        p <-  plot_ctr_treemap(
                year = as.numeric(reactiveParameters$year),
                country_asylum_iso3c = reactiveParameters$country,
                pop_type = input$pop_type)
    # ## Plot Population type per year
      } else if( thisPlot == "plot_ctr_population_type_per_year"){
        p <-  plot_ctr_population_type_per_year(
                year = as.numeric(reactiveParameters$year),
                country_asylum_iso3c = reactiveParameters$country,
                pop_type = input$pop_type,
                lag = input$lag)
    # # 2. Origin
    # ## Plot Main country of origin  in one specific country - Absolute value
      } else if( thisPlot == "plot_ctr_population_type_abs"){
        p <-  plot_ctr_population_type_abs(
                year = as.numeric(reactiveParameters$year),
                country_asylum_iso3c = reactiveParameters$country,
                pop_type = input$pop_type,
                top_n_countries = input$top_n_countries,
                show_diff_label = FALSE)
    # ## Plot Main country of origin in one specific country - Percentage
      } else if( thisPlot == "plot_ctr_population_type_perc"){
        p <-  plot_ctr_population_type_perc(
                year = as.numeric(reactiveParameters$year),
                country_asylum_iso3c = reactiveParameters$country,
                pop_type = input$pop_type,
                top_n_countries = input$top_n_countries)
    # ## Plot Increases and Decreases in Population Groups
      } else if( thisPlot == "plot_ctr_diff_in_pop_groups"){
        p <-  plot_ctr_diff_in_pop_groups(
                year = as.numeric(reactiveParameters$year),
                country_asylum_iso3c = reactiveParameters$country,
                pop_type = input$pop_type)
    # ## Plot Origin History
      } else if( thisPlot == "plot_ctr_origin_history"){
        p <-  plot_ctr_origin_history(
                year = as.numeric(reactiveParameters$year),
                country_asylum_iso3c = reactiveParameters$country,
                pop_type = input$pop_type,
                lag = input$lag,
                otherprop = input$otherprop)
    # # 3. Destination 
    # ## Plot Main Destination from  one specific country 
      } else if( thisPlot == "plot_ctr_destination"){
        p <-  plot_ctr_destination(
                year = as.numeric(reactiveParameters$year),
                country_asylum_iso3c = reactiveParameters$country,
                pop_type = input$pop_type )
    # ## plot recognition rate for a nationality
      } else if( thisPlot == "plot_ctr_origin_recognition"){
        p <-  plot_ctr_origin_recognition(
                year = as.numeric(reactiveParameters$year),
                country_asylum_iso3c = reactiveParameters$country,
                pop_type = input$pop_type, 
                top_n_countries = input$top_n_countries,
                measure  = input$measure ,
                order_by = input$order_by)
    # # 4. Profile
    # ## Plot Age Pyramid
      }  else if( thisPlot == "plot_ctr_pyramid"){
        p <-  plot_ctr_pyramid(
                year = as.numeric(reactiveParameters$year),
                country_asylum_iso3c = reactiveParameters$country,
                pop_type = input$pop_type )
    # ## Plot locations within countries
      } else if( thisPlot == "plot_ctr_location"){
        p <-  plot_ctr_location(
                year = as.numeric(reactiveParameters$year),
                country_asylum_iso3c = reactiveParameters$country,
                pop_type = input$pop_type)
    # # 5. Processing
    # ## Plot Refugee Recognition rate in Country
      } else if( thisPlot == "plot_ctr_recognition"){
        p <-  plot_ctr_recognition(
                year = as.numeric(reactiveParameters$year),
                country_asylum_iso3c = reactiveParameters$country,
                top_n_countries = input$top_n_countries,
                measure  = input$measure ,
                order_by = input$order_by)
    # ## Asylum Applications & Decision over time
      } else if( thisPlot == "plot_ctr_asylum"){
        p <-  plot_ctr_asylum(
                year = as.numeric(reactiveParameters$year),
                country_asylum_iso3c = reactiveParameters$country,
                lag = input$lag)
    # ## Asylum Processing
      } else if( thisPlot == "plot_ctr_process"){
        p <-  plot_ctr_process(
                year = as.numeric(reactiveParameters$year),
                country_asylum_iso3c = reactiveParameters$country,
                otherprop = input$otherprop)
    # ## Average Asylum Processing Time
      } else if( thisPlot == "plot_ctr_processing_time"){
        p <-  plot_ctr_processing_time(
                year = as.numeric(reactiveParameters$year),
                country_asylum_iso3c = reactiveParameters$country,
                #country_origin_iso3c = input$origin,
                procedureType = input$procedureType)
    # # 6. Solutions 
    # ## Plot Solution Over time 
      } else if( thisPlot == "plot_ctr_solution"){
        p <-  plot_ctr_solution(
                year = as.numeric(reactiveParameters$year),
                country_asylum_iso3c = reactiveParameters$country,
                pop_type = input$pop_type)
    # # 7.Migrant 
    # ## Plot Ratio Refugee Migrant 
      } else if( thisPlot == "plot_ctr_disp_migrant"){
        p <-  plot_ctr_disp_migrant(
                year = as.numeric(reactiveParameters$year),
                country_asylum_iso3c = reactiveParameters$country )
        
        ## Default in case...
      } else {
        p <- ggplot2::ggplot() +  
          ggplot2::annotate("text", x = 1, y = 1, size = 11, 
                            label = "There was a problem" ) +  
          ggplot2::theme_void() 
      }
      
      ## Now adding title and subtitle...
      if (input$title != "") { 
        p <- p + labs(title = input$title)}
      if (input$subtitle != "") {
        p <- p + labs(subtitle = input$subtitle)}
      
      #reactLocal$chart <- p
      p 
      })
    
    ## Button to manage chart download
    output$dl <- downloadHandler(
            filename = function() {
              paste(thisPlot, Sys.Date(), '.png', sep='')
            },
            content = function(con) {
              ggsave(con,
                     reactLocal$p, 
                     device = "png", 
                     width = 8, 
                     height = 5)
            })
    
    ## Button to display syntax for reproducibility...
    # https://daattali.com/shiny/shinyalert-demo/
    # ui
    #       useShinyalert() 
    # 
    # server  
    #   shinyalert(
    #     title = "Analysis Reproducibility",
    #     text = "Below is a the script you can use to reproduce this chart",
    #     size = "l", 
    #     closeOnEsc = TRUE,
    #     closeOnClickOutside = FALSE,
    #     html = FALSE,
    #     type = "success",
    #     showConfirmButton = TRUE,
    #     showCancelButton = FALSE,
    #     confirmButtonText = "OK",
    #     confirmButtonCol = "#0072BC",
    #     timer = 0,
    #     imageUrl = "",
    #     animation = FALSE
    #   )
    
  })
}
    
## To be copied in the UI
# mod_plotviz_ui("migrants_1")
    
## To be copied in the server
# mod_plotviz_server("migrants_1")

