# WARNING - Generated by {fusen} from /dev/dev_golem_module.Rmd: do not edit by hand

#' processing UI Function
#'
#' @description A shiny Module.
#'
#' @param id,input,output,session Internal parameters for {shiny}.
#'
#' @noRd 
#'
#' @importFrom shiny NS tagList 
mod_processing_ui <- function(id){
  ns <- NS(id)
  tagList(
        plotOutput(ns("plot_ctr_process"))
  )
}
    
#' processing Server Functions
#'
#' @noRd 
mod_processing_server <- function(id, reactiveParameters){
  moduleServer( id, function(input, output, session){
    ns <- session$ns
    output$plot_ctr_process <- renderPlot({
                        plot_ctr_process(
              year = as.numeric(reactiveParameters$year),
              country_asylum_iso3c = reactiveParameters$country)
                             })
 
  })
}
    
## To be copied in the UI
# mod_processing_ui("processing_1")
    
## To be copied in the server
# mod_processing_server("processing_1")

