# WARNING - Generated by {fusen} from dev/dev_plot_Country.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot Average processing time from registration to first instance asylum decision
#'
#' This indicator measures the average number of days from the date of completion of registration of the asylum application to the date of notification of first instance asylum decision for all persons who were notified of a first instance RSD/asylum decision during the reporting period.
#'
#' Status determination procedures are a core protection function and the principle mechanism through which international protection needs of Persons of Concern may be determined in accordance with the key provisions of the 1951 Convention and 1967 Protocol relating to the Status of Refugees, the 1954 Convention relating to the Status of Stateless Persons, or relevant regional refugee protection instruments. Status determination procedures are therefore central to the full and effective enjoyment of the universal right to seek and enjoy asylum and the specific rights guaranteed by the above instruments.
#'
#' A prolonged waiting period during the status determination procedure is an important indicator of the state of efficiency, fairness, adaptability integrity and hence, overall quality of the national asylum or, depending on the context, UNHCR Mandate RSD procedure, including the timeliness and effectiveness of the overall protection response in the country.
#'
#'  (RBM Outcome Indicator 2.1) - see [UNHCR Intranet](https://intranet.unhcr.org/content/dam/unhcr/intranet/protection-operations/compass/en/guidance/3/coreindicatorsmetadata/2.0%20Core%20Indicator%20Metadata%2004%2010%202021.pdf#page=67) - Credit to Hisham Galal for the chart initial idea and script
#'
#' @param year Numeric value of the year (for instance 2020)
#' @param country_asylum_iso3c Character value with the ISO-3 character code of the Country of Asylum
#'
#' @param country_origin_iso3c Character value with the ISO-3 character code of the Country of Asylum - if NUL then all countries are included
#'
#' @param procedureType indicates whether "G" (Government) "J" (Joint) "U" (UNHCR)
#' @importFrom ggplot2  ggplot  aes  coord_flip   element_blank element_line
#'             element_text expansion geom_bar geom_col geom_hline unit stat_summary
#'             geom_label geom_text labs  position_stack  scale_color_manual scale_colour_manual guides guide_legend
#'             geom_text guide_axis facet_wrap vars geom_area annotate
#'             scale_fill_manual scale_x_continuous scale_x_discrete  scale_y_continuous   sym theme  scale_fill_manual
#' @importFrom utils  head
#' @importFrom tidyselect where
#' @importFrom stringr  str_replace
#' @importFrom scales cut_short_scale label_percent label_number breaks_pretty
#' @importFrom tidyr pivot_longer
#' @importFrom dplyr  desc select  case_when lag mutate group_by filter summarise ungroup
#'               pull distinct n arrange across slice left_join last transmute
#' @importFrom purrr detect_index
#' @importFrom lubridate date_decimal interval days make_date
#' @importFrom unhcrthemes theme_unhcr
#'
#' @return a ggplot2 object
#'
#' @export
#' @examples
#' plot_ctr_processing_time(
#'   year = 2024,
#'   country_asylum_iso3c = "ARG"
#' )
#'
#'
#' plot_ctr_processing_time(
#'   year = 2024,
#'   country_asylum_iso3c = "USA"
#' )
#'
#' ## Display a filtered version of the chart for a specific country and procedure
#' plot_ctr_processing_time(
#'   year = 2024,
#'   country_asylum_iso3c = "EGY",
#'   country_origin_iso3c = "ERI",
#'   procedureType = "U"
#' )
plot_ctr_processing_time <- function(year = 2024,
                                     country_asylum_iso3c = country_asylum_iso3,
                                     country_origin_iso3c = NULL,
                                     procedureType = NULL) {
  country_name_text <- refugees::population |>
    dplyr::filter(coa_iso == country_asylum_iso3c) |>
    dplyr::distinct(coa_name) |>
    dplyr::pull() |>
    utils::head(1)

  if (is.null(country_origin_iso3c)) {
    originfilterlab <- ""
  } else {
    originfilterlab <- refugees::population |>
      dplyr::filter(coo_iso == country_origin_iso3c) |>
      dplyr::distinct(coo_name) |>
      dplyr::pull() |>
      utils::head(1)
  }

  # Procedure filtering is not supported with refugees package in this version
  procedurefilterlab <- ""

  filterlab <- paste0(
    dplyr::if_else(originfilterlab == "",
      "",
      paste0(", filtered for nationals from ", originfilterlab)
    )
  )

  apps <- refugees::asylum_applications |>
    dplyr::filter(coa_iso == country_asylum_iso3c)

  if (!is.null(country_origin_iso3c)) {
    apps <- apps |> dplyr::filter(coo_iso == country_origin_iso3c)
  }

  apps <- apps |>
    dplyr::mutate(DecisionTypeCode = "FI") |> # Assumption: All applications are considered
    dplyr::group_by(year, coa_iso) |>
    dplyr::summarize(NumberApplications = sum(applied, na.rm = TRUE)) |>
    dplyr::rename(CountryAsylumCode = coa_iso) |>
    dplyr::ungroup()

  decs <- refugees::asylum_decisions |>
    dplyr::filter(coa_iso == country_asylum_iso3c)

  if (!is.null(country_origin_iso3c)) {
    decs <- decs |> dplyr::filter(coo_iso == country_origin_iso3c)
  }

  decs <- decs |>
    dplyr::mutate(DecisionTypeCode = "FI") |> # Assumption: All decisions are considered
    dplyr::group_by(year, coa_iso) |>
    dplyr::summarize(TotalDecided = sum(dec_total, na.rm = TRUE)) |>
    dplyr::rename(CountryAsylumCode = coa_iso) |>
    dplyr::ungroup()

  data <-
    dplyr::left_join(
      apps |> dplyr::select(year, CountryAsylumCode, NumberApplications),
      decs |> dplyr::select(year, CountryAsylumCode, TotalDecided),
      by = c("year", "CountryAsylumCode")
    ) |>
    dplyr::arrange(year) |>
    dplyr::mutate(dplyr::across(
      c(NumberApplications, TotalDecided),
      ~ tidyr::replace_na(., 0)
    )) |>
    dplyr::transmute(
      year = dplyr::if_else(year == dplyr::last(year),
        year + .5,
        year + 1
      ),
      apps = cumsum(NumberApplications),
      decs = cumsum(TotalDecided)
    )

  idx <- purrr::detect_index(data$apps, ~ . < dplyr::last(data$decs),
    .dir = "backward"
  )

  t <- lubridate::date_decimal(data$year[idx] +
    (dplyr::last(data$decs) - data$apps[idx]) /
      (data$apps[idx + 1] - data$apps[idx]))

  stat <- lubridate::interval(t, lubridate::make_date(2022, 6, 30)) / lubridate::days()

  data2 <- data |>
    tidyr::pivot_longer(-year,
      names_to = "flow",
      values_to = "n"
    )


  p <- data2 |>
    ggplot2::ggplot(ggplot2::aes(year,
      n,
      fill = flow
    )) +
    ggplot2::geom_area(position = "identity") +
    ## highlight the main indicator!
    ggplot2::annotate("segment",
      x = lubridate::decimal_date(t),
      y = dplyr::last(data$decs),
      xend = dplyr::last(data$year),
      yend = dplyr::last(data$decs)
    ) +
    ggplot2::annotate("text",
      x = 2020,
      y = dplyr::last(data$decs),
      vjust = -.5,
      label = paste0(round(stat), " days")
    ) +
    ggplot2::scale_y_continuous(labels = scales::label_comma()) +
    ggplot2::scale_fill_manual(
      labels = c(
        decs = "Decisions",
        apps = "Applications"
      ),
      values = c(
        decs = "#0072BC",
        apps = "#FAEB00"
      ),
      name = NULL
    ) +
    ggplot2::labs(
      title = stringr::str_wrap("Average Processing Time from Asylum Registration to First Instance Decision", 100),
      subtitle = paste0("In ", country_name_text, ", comparative cumulative applications and decisions with gap measured in days as of ", year, filterlab),
      x = NULL,
      y = "Cumulative total",
      caption = "Source: UNHCR.org/refugee-statistics"
    ) +
    ggplot2::guides(fill = ggplot2::guide_legend(reverse = TRUE)) +
    unhcrthemes::theme_unhcr(
      font_size = 14,
      grid = "Y"
    ) +
    ggplot2::theme(legend.position = "top")

  return(p)
}
