# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

#' Tree map of Population Groups within a country
#'
#' @param year Numeric value of the year (for instance 2020)
#' @param country_asylum_iso3c Character value with the ISO-3 character code of the Country of Asylum
#' @param pop_type Vector of character values. Possible population type (e.g.: REF, IDP, ASY, VDA, OOC, STA)
#' 
#' @export
#'

#' @examples
#' # 
#' plot_ctr_treemap(year = 2021,
#'                             country_asylum_iso3c = "USA",
#'                             pop_type = c("REF", "ASY")
#'          )
#' 
plot_ctr_treemap <- function(year = 2021,
                     country_asylum_iso3c = country_asylum_iso3c,
                     pop_type = pop_type) {
  require(ggplot2)
  require(tidyverse)
  require(scales)

  datatree <-  unhcrdatapackage::end_year_population_totals_long  |> 
    dplyr::filter(Year == year,  #### Parameter
                  CountryAsylumCode == country_asylum_iso3c #### Parameter
    ) |> 
    dplyr::select(-c(Year)) |> 
    dplyr::group_by(CountryAsylumName,  Population.type, 
                    Population.type.label, Population.type.label.short) |> 
    dplyr::summarise(dplyr::across(where(is.numeric), sum)) |> 
    dplyr::ungroup() 
  
  treemap <- ggplot(datatree, 
       aes(area = Value, 
           fill = Population.type,
           label = paste0(round(100*Value/sum(Value),1), 
                          "%\n", 
                          Population.type.label))) +
         treemapify::geom_treemap() +
         treemapify::geom_treemap_text(colour = "white",
                           place = "centre", size = 25) +
         scale_fill_manual( values = c(   "IDP" = "#00B398",
                                          "VDA"="#EF4A60",
                                          "ASY" = "#18375F",
                                          "REF" = "#0072BC",
                                          "OOC" ="#8395b9",
                                          "STA"="#E1CC0D")) +
         
      unhcrthemes::theme_unhcr(font_size = 12, grid = "Y", axis = "x", axis_title = "y", legend = FALSE) +
         theme(legend.position = "none") +
         ## and the chart labels
         labs(title = paste0("Population of Concern in ", country_asylum_iso3c),
              subtitle = paste0("As of ", year, ", a total of ", format(round(sum(datatree$Value), -3),  big.mark=","), " Individuals"),
              x = "",
              y = "",
              caption = "Source: UNHCR.org/refugee-statistics  ")  

print(treemap)
}

