# WARNING - Generated by {fusen} from dev/dev_plot_Region.Rmd: do not edit by hand # nolint: line_length_linter.

#' Evolution over time 
#' 
#' Display evoluation over time for specific population group (one or many) and 
#' defined number of years (lag)
#' 
#' @param year Numeric value of the year (for instance 2020)
#' @param region Character value with the related UNHCR bureau - when left null, it will display the whole world
#' @param lag Number of year to used as comparison base 
#' @param pop_type Character value. Possible population type (e.g.: REF, IDP, ASY,   OIP, OOC, STA)
#' 
#' @importFrom ggplot2  ggplot  aes  coord_flip   element_blank element_line
#'             element_text expansion geom_bar geom_col geom_hline unit stat_summary
#'             geom_label geom_text labs  position_stack  scale_color_manual
#'              scale_colour_manual 
#'             geom_text geom_line
#'             scale_fill_manual scale_x_continuous scale_x_discrete  scale_y_continuous   sym theme 
#' @importFrom dplyr  desc select  case_when lag mutate group_by filter summarise ungroup
#'               pull distinct n arrange across slice left_join
#' @importFrom stringr str_replace  
#' @importFrom scales cut_short_scale label_percent label_number breaks_pretty pretty_breaks
#' @importFrom unhcrthemes theme_unhcr unhcr_pal
#' 
#' @return a ggplot2 object
#' 
#' @export
#' @examples
#' plot_reg_population_type_per_year(
#'   year = 2024,
#'   lag = 5,
#'   region = "The Americas",
#'   pop_type = c("REF", "ASY", "IDP", "OIP", "STA", "OOC")
#' )
plot_reg_population_type_per_year <- function(year = 2024,
                                              region = "The Americas",
                                              lag = 5,
                                              pop_type = c("REF", "ASY", "IDP", "OIP", "STA", "OOC")) {

  # Check if pop_type is a list or a single character
  if (length(pop_type) > 1) {
    pop_type_label <- pop_type
  } else {
    pop_type_label <- pop_type
  }

  pop_type_label_dict <- c(
    "REF" = "Refugees",
    "ASY" = "Asylum-seekers",
    "IDP" = "Internally displaced persons",
    "OIP" = "Other people in need of international protection",
    "STA" = "Stateless people",
    "OOC" = "Others of concern to UNHCR",
    "HST" = "Host community"
  )

  df <- refugees::population |>
    dplyr::filter(year >= (!!year - lag) & year <= !!year) |>
    dplyr::mutate(unhcr_region = countrycode::countrycode(coa_iso, "iso3c", "unhcr.region")) |>
    dplyr::filter(unhcr_region == region) |>
    tidyr::pivot_longer(
      cols = c(refugees, asylum_seekers, idps, oip, stateless, ooc, hst),
      names_to = "population_type",
      values_to = "value"
    ) |>
    dplyr::mutate(
      population_type_label = dplyr::case_when(
        population_type == "refugees" ~ "REF",
        population_type == "asylum_seekers" ~ "ASY",
        population_type == "idps" ~ "IDP",
        population_type == "oip" ~ "OIP",
        population_type == "stateless" ~ "STA",
        population_type == "ooc" ~ "OOC",
        population_type == "hst" ~ "HST",
        TRUE ~ "Other"
      )
    ) |>
    dplyr::filter(population_type_label %in% pop_type) |>
    dplyr::group_by(year, population_type_label) |>
    dplyr::summarise(value = sum(value, na.rm = TRUE), .groups = "drop") |>
    dplyr::mutate(population_type_name = dplyr::recode(population_type_label, !!!pop_type_label_dict))

  p <- ggplot2::ggplot(df, ggplot2::aes(x = year, y = value, colour = population_type_label)) +
    ggplot2::geom_line(size = 1) +
    ggplot2::geom_hline(yintercept = 0, size = 1.1, colour = "#333333") +
    ggplot2::scale_y_continuous(labels = scales::label_number(scale_cut = scales::cut_short_scale())) +
    ggplot2::xlim(c(year - lag, year + 1)) +
    unhcrthemes::scale_color_unhcr_d(palette = "pal_unhcr") +
    ggplot2::geom_label(
      data = df |> dplyr::filter(year == max(year)),
      ggplot2::aes(
        x = year + .5,
        y = value,
        label = population_type_name,
        color = population_type_label
      ),
      hjust = 0,
      vjust = 0.5,
      fill = "white",
      label.size = NA,
      family = "Lato",
      size = 4
    ) +
    unhcrthemes::theme_unhcr(
      grid = "Y",
      axis = "x",
      axis_title = "y",
      font_size = 14
    ) +
    ggplot2::theme(
      legend.position = "none",
      panel.grid.major.y = ggplot2::element_line(color = "#cbcbcb"),
      panel.grid.major.x = ggplot2::element_blank(),
      panel.grid.minor = ggplot2::element_blank()
    ) +
    ggplot2::labs(
      title = paste0("Evolution of Population of Concern in ", region),
      subtitle = paste0("Evolution in the past ", lag, " years"),
      x = "",
      y = "",
      caption = "Source: UNHCR.org/refugee-statistics"
    )

  return(p)
}
