# WARNING - Generated by {fusen} from dev/dev_plot_Country.Rmd: do not edit by hand # nolint: line_length_linter.

#' Create a map with symbol proportional to population data by location within country
#'
#' @param year Numeric value of the year  (for instance 2022).
#'             If the data is not yet available for that year (aka still in the mid year reporting stage),
#'              it will automatically fall back on the previous year
#'
#' @param country_asylum_iso3c Character value with the ISO-3 character code of the Country of Asylum
#' @param pop_type Vector of character values. Possible population type (e.g.: REF, IDP, ASY, OIP, OOC, STA)
#' @param  mapbackground can be "osm" (default), "stamen-toner" , "stamen-terrain","stamen-watercolor".
#'            Other mapbackground requires an API key and were not considered
#'
#' @importFrom ggplot2  ggplot  aes  coord_flip   element_blank element_line
#'             element_text expansion geom_bar geom_col geom_hline unit stat_summary
#'             geom_label geom_text labs  position_stack  geom_point
#'             scale_color_manual scale_colour_manual
#'             scale_size_continuous element_rect
#'             geom_text .pt theme_void
#'             scale_fill_manual scale_x_continuous scale_x_discrete  scale_y_continuous   sym theme
#' @importFrom utils  head
#' @importFrom tidyselect where
#' @importFrom stringr  str_replace str_detect  str_glue
#' @importFrom scales cut_short_scale label_percent label_number breaks_pretty
#' @importFrom stats  reorder aggregate  setNames
#' @importFrom dplyr  desc select  case_when lag mutate group_by filter summarise ungroup
#'               pull distinct n arrange across slice left_join
#' @importFrom tidyr pivot_longer pivot_wider
#' @importFrom ggspatial geom_sf coord_sf
#' @importFrom sf st_as_sf st_set_crs st_bbox
#' @importFrom rnaturalearth ne_countries
#' @import rnaturalearthdata
#' @importFrom ggrepel geom_label_repel
#' @importFrom grDevices hcl.colors
#' @importFrom OpenStreetMap openmap openproj autoplot.OpenStreetMap
#' @importFrom unhcrthemes theme_unhcr
#'
#' @return a ggplot2 object
#'
#' @export
#'
#' @examples
#' # plot_ctr_location(year = 2024,
#' #                  country_asylum_iso3c = "COL",
#' #                  pop_type = c("ASY", "REF", "OIP"))
#' #
#' # plot_ctr_location(year = 2021,
#' #                  country_asylum_iso3c = "COL",
#' #                  pop_type = c("IDP"))
#' #
#' # plot_ctr_location(year = 2024,
#' #                  country_asylum_iso3c = "CAN",
#' #                  pop_type = c("ASY", "REF", "OIP"))
#' #
#' # plot_ctr_location(year = 2021,
#' #                  country_asylum_iso3c = "MEX",
#' #                  pop_type = c("ASY", "REF", "OIP"))
plot_ctr_location <- function(year,
                              country_asylum_iso3c,
                              pop_type,
                              mapbackground = "osm") {
  country_name_text <- refugees::population |>
    dplyr::filter(coa_iso == country_asylum_iso3c) |>
    dplyr::distinct(coa_name) |>
    dplyr::pull() |>
    head(1)

  if (length(country_name_text) == 0) country_name_text <- country_asylum_iso3c

  # Get country geometry
  country_sf <- rnaturalearth::ne_countries(scale = "medium", returnclass = "sf") |>
    dplyr::filter(iso_a3 == country_asylum_iso3c)

  if (nrow(country_sf) == 0) {
    p <- ggplot2::ggplot() +
      ggplot2::annotate("text", x = 1, y = 1, label = paste0("Map data not available for ", country_asylum_iso3c)) +
      ggplot2::theme_void()
    return(p)
  }

  # Calculate centroid for label
  centroid <- suppressWarnings(sf::st_centroid(country_sf))
  coords <- sf::st_coordinates(centroid)

  p <- ggplot2::ggplot() +
    ggplot2::geom_sf(data = country_sf, fill = "#e6e6e6", color = "#333333") +
    ggplot2::annotate("text",
      x = coords[1],
      y = coords[2],
      label = "Sub-national location data\ncurrently unavailable",
      color = "#333333",
      size = 4,
      fontface = "italic"
    ) +
    ggplot2::labs(
      title = paste0("Location of Populations of Concern in ", country_name_text),
      subtitle = paste0("As of ", year),
      caption = "Source: UNHCR.org/refugee-statistics"
    ) +
    ggplot2::theme_void()

  return(p)
}
