# WARNING - Generated by {fusen} from dev/dev_plot_Country.Rmd: do not edit by hand # nolint: line_length_linter.

#' Asylum Applications & Decision over time
#' This charts allow to visualize trends in terms of asylum applications, decision and refugee status recognition
#'
#' @param year Numeric value of the year (for instance 2020)
#' @param country_asylum_iso3c Character value with the ISO-3 character code of the Country of Asylum
#' @param lag Number of year to used as comparison base
#' @importFrom ggplot2 ggplot aes coord_flip element_blank element_line
#'             element_text expansion geom_bar geom_col geom_hline unit stat_summary
#'             geom_label geom_text labs position_stack scale_color_manual scale_colour_manual
#'             geom_text guide_axis facet_wrap vars
#'             scale_fill_manual scale_x_continuous scale_x_discrete scale_y_continuous sym theme
#' @importFrom utils head
#' @importFrom dplyr desc select case_when lag mutate group_by filter summarize ungroup
#'               pull distinct n arrange across slice left_join rename inner_join recode
#' @importFrom tidyr pivot_longer
#' @importFrom unhcrthemes theme_unhcr scale_fill_unhcr_d
#' @importFrom scales pretty_breaks cut_short_scale label_number
#'
#' @return a ggplot2 object
#'
#' @export
#' @examples
#' plot_ctr_asylum(
#'   year = 2024,
#'   country_asylum_iso3c = "ECU",
#'   lag = 10
#' )
plot_ctr_asylum <- function(year = 2024,
                            country_asylum_iso3c,
                            lag = 10) {
  
  # 1. Get Country Name
  country_name_text <- refugees::population |>
    dplyr::filter(coa_iso == country_asylum_iso3c) |>
    dplyr::distinct(coa_name) |>
    dplyr::pull() |>
    utils::head(1)
  
  # 2. Prepare Applications Data
  apps <- refugees::asylum_applications |>
    dplyr::filter(coa_iso == country_asylum_iso3c) |>
    dplyr::group_by(year, coa_iso) |>
    dplyr::summarize(NumberApplications = sum(applied, na.rm = TRUE), .groups = "drop") |>
    dplyr::rename(CountryAsylumCode = coa_iso)
  
  # 3. Prepare Decisions Data (FIXED SECTION)
  decs <- refugees::asylum_decisions |>
    dplyr::filter(coa_iso == country_asylum_iso3c) |>
    dplyr::group_by(year, coa_iso) |>
    dplyr::summarize(
      Recognized = sum(dec_recognized, na.rm = TRUE),
      ComplementaryProtection = sum(dec_other, na.rm = TRUE),
      OtherwiseClosed = sum(dec_closed, na.rm = TRUE),
      Rejected = sum(dec_rejected, na.rm = TRUE),
      TotalDecided = sum(dec_total, na.rm = TRUE), 
      .groups = "drop"
    ) |>
    dplyr::rename(CountryAsylumCode = coa_iso)
  
  # 4. Join and Reshape
  data <- dplyr::inner_join(apps, decs, by = c("year", "CountryAsylumCode")) |>
    dplyr::filter(year >= (!!year - lag)) |> # Use !! to unquote the function argument
    dplyr::select(year, NumberApplications, Recognized, TotalDecided) |>
    tidyr::pivot_longer(
      cols = c(NumberApplications, TotalDecided, Recognized), # Explicit columns safer than ranges
      names_to = "AsylumStage",
      values_to = "Total",
      values_drop_na = TRUE
    )
  
  # 5. Factor Management
  data$AsylumStage <- dplyr::recode(data$AsylumStage,
                                    "NumberApplications" = "Total Number of Applications",
                                    "TotalDecided" = "Total Number of Decisions",
                                    "Recognized" = "Number of Refugee Status Recognition Decisions"
  )
  
  data$AsylumStage <- factor(data$AsylumStage, levels = c(
    "Total Number of Applications",
    "Total Number of Decisions",
    "Number of Refugee Status Recognition Decisions"
  ))
  
  # 6. Plotting
  p <- ggplot2::ggplot() +
    ggplot2::geom_bar(
      data = data,
      ggplot2::aes(x = year, y = Total, fill = AsylumStage),
      stat = "identity", position = "dodge", width = 0.8
    ) +
    unhcrthemes::scale_fill_unhcr_d(palette = "pal_unhcr") +
    ggplot2::scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
    ggplot2::scale_y_continuous(labels = scales::label_number(accuracy = 1, scale_cut = scales::cut_short_scale())) +
    ggplot2::labs(
      title = paste0("Asylum Applications & Decisions | ", country_name_text, " ", (year - lag), " - ", year),
      subtitle = "Note: Under certain circumstances, one person may have more than one application",
      x = "",
      y = "",
      caption = "Source: UNHCR.org/refugee-statistics"
    ) +
    unhcrthemes::theme_unhcr(
      font_size = 14,
      grid = "Y" # Standard bar charts usually look better with Y grid lines only
    ) +
    ggplot2::theme(
      panel.grid.major.y = ggplot2::element_line(color = "#cbcbcb"),
      panel.grid.major.x = ggplot2::element_blank(),
      legend.position = "bottom" # Usually better for long legends
    )
  
  return(p)
}

