# WARNING - Generated by {fusen} from dev/dev_plot_Region.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot Regional Solution
#'
#' @param year Numeric value of the year (for instance 2020)
#' @param region Character value including the UNHCR region
#' @param lag Number of year to used as comparison base
#' @param label_font_size Numeric value for label font size
#' @param category_font_size Numeric value for axis text font size
#' @export
#' @examples
#' plot_reg_solution(
#'     year = 2024,
#'     region = "The Americas",
#'     label_font_size = 4,
#'     category_font_size = 10
#' )
plot_reg_solution <- function(year = 2024,
                              region = "The Americas",
                              lag = 10,
                              label_font_size = 4,
                              category_font_size = 10) {
    solutions_long <- refugees::solutions |>
        dplyr::mutate(unhcr_region = countrycode::countrycode(coa_iso, "iso3c", "unhcr.region")) |>
        dplyr::filter(unhcr_region == region & year >= (!!year - lag) & year <= !!year) |>
        tidyr::pivot_longer(
            cols = c(naturalisation, resettlement, returned_refugees),
            names_to = "solution_type",
            values_to = "value"
        ) |>
        dplyr::group_by(year, solution_type) |>
        dplyr::summarise(value = sum(value, na.rm = TRUE), .groups = "drop")

    p <- ggplot2::ggplot(solutions_long, ggplot2::aes(x = year, y = value, colour = solution_type)) +
        ggplot2::geom_line(linewidth = 1) +
        ggplot2::geom_hline(yintercept = 0, linewidth = 1.1, colour = "#333333") +
        ggplot2::scale_y_continuous(labels = scales::label_number(scale_cut = scales::cut_short_scale())) +
        ggplot2::xlim(c(year - lag, year + 2)) +
        ggplot2::scale_colour_manual(
            values = c(
                "naturalisation" = "#a6cee3",
                "resettlement" = "#1f78b4",
                "returned_refugees" = "#b2df8a"
            ),
            labels = c(
                "naturalisation" = "Naturalisation",
                "resettlement" = "Resettlement",
                "returned_refugees" = "Returns"
            )
        ) +
        # ggplot2::geom_label(
        #     data = solutions_long |> dplyr::filter(year == max(year)),
        #     ggplot2::aes(
        #         x = year + .5,
        #         y = value,
        #         label = solution_type,
        #         color = solution_type
        #     ),
        #     hjust = 0,
        #     vjust = 0.5,
        #     fill = "white",
        #     linewidth = NA,
        #     family = "Lato",
        #     size = label_font_size
        # ) +
        unhcrthemes::theme_unhcr(
            grid = "Y",
            axis = "x",
            axis_title = "y",
            font_size = 14
        ) +
        ggplot2::theme(
            legend.position = "top",
            legend.justification = "left",
            legend.title = ggplot2::element_blank(),
            panel.grid.major.y = ggplot2::element_line(color = "#cbcbcb"),
            panel.grid.major.x = ggplot2::element_blank(),
            panel.grid.minor = ggplot2::element_blank(),
            axis.text.x = ggplot2::element_text(size = category_font_size)
        ) +
        ggplot2::labs(
            title = paste0("Solution for Displacement in ", region),
            subtitle = paste0("Evolution from ", year - lag, " to ", year),
            x = "",
            y = "",
            caption = "Source: UNHCR.org/refugee-statistics"
        )

    return(p)
}
