# WARNING - Generated by {fusen} from dev/dev_plot_Region.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot Regional Share
#'
#' @param year Numeric value of the year (for instance 2020)
#' @param region Character value including the UNHCR region
#' @param pop_type Vector of character values. Possible population type
#' @param label_font_size Numeric value for label font size
#' @export
#' @examples
#' plot_reg_share(
#'     year = 2024,
#'     region = "The Americas",
#'     label_font_size = 15
#' )
plot_reg_share <- function(year = 2024,
                           region = "The Americas",
                           pop_type = "REF",
                           label_font_size = 15) {
    pop_typelabel <- dplyr::case_when(
        pop_type == "REF" ~ "Refugees",
        pop_type == "IDP" ~ "Internally displaced persons",
        pop_type == "ASY" ~ "Asylum seekers",
        pop_type == "OOC" ~ "Others of concern to UNHCR",
        pop_type == "STA" ~ "Stateless Persons",
        pop_type == "OIP" ~ "Other people in need of international protection",
        pop_type == "HCO" ~ "Host community"
    )

    datatree <- refugees::population |>
        dplyr::filter(year == !!year) |>
        dplyr::mutate(unhcr_region = countrycode::countrycode(coa_iso, "iso3c", "unhcr.region")) |>
        tidyr::pivot_longer(
            cols = c(refugees, asylum_seekers, idps, oip, stateless, ooc, hst),
            names_to = "population_type",
            values_to = "value"
        ) |>
        dplyr::mutate(population_type_label = dplyr::case_when(
            population_type == "refugees" ~ "REF",
            population_type == "asylum_seekers" ~ "ASY",
            population_type == "idps" ~ "IDP",
            population_type == "oip" ~ "OIP",
            population_type == "stateless" ~ "STA",
            population_type == "ooc" ~ "OOC",
            population_type == "hst" ~ "HCO",
            TRUE ~ "Other"
        )) |>
        dplyr::filter(population_type_label %in% pop_type) |>
        dplyr::mutate(Compare = ifelse(unhcr_region == region, region, "Rest of the World")) |>
        dplyr::group_by(year, Compare, population_type_label, population_type) |>
        dplyr::summarise(value = sum(value, na.rm = TRUE), .groups = "drop") |>
        dplyr::mutate(freq = scales::label_percent(accuracy = .1, suffix = "%")(value / sum(value)))

    p <- ggplot2::ggplot(
        datatree,
        ggplot2::aes(
            area = value,
            fill = Compare,
            label = paste0(format(round(datatree$value, -3), big.mark = ","), "\n in ", Compare)
        )
    ) +
        treemapify::geom_treemap() +
        treemapify::geom_treemap_text(
            colour = "white",
            place = "centre", size = label_font_size,
            family = "Lato"
        ) +
        unhcrthemes::scale_fill_unhcr_d(palette = "pal_unhcr") +
        unhcrthemes::theme_unhcr(font_size = 14) +
        ggplot2::theme(legend.position = "none") +
        ggplot2::labs(
            title = paste0("Share of ", pop_typelabel, " within ", region),
            subtitle = stringr::str_wrap(paste0(
                "As of ", year,
                ", about ",
                datatree |> dplyr::filter(Compare == region) |> dplyr::select(freq) |> dplyr::pull(),
                " of that global population category are hosted in the region"
            ), 80),
            x = "",
            y = "",
            caption = "Source: UNHCR.org/refugee-statistics"
        )

    return(p)
}
