# WARNING - Generated by {fusen} from dev/dev_plot_Country.Rmd: do not edit by hand # nolint: line_length_linter.

#' Summary Key Figures
#'  Key figures can be highlighted with humanitarian icons
#'   https://fontawesome.com/icons/categories/humanitarian
#' @param year Numeric value of the year (for instance 2020)
#' @param country_asylum_iso3c Character value with the ISO-3 character code of the Country of Asylum
#' @return ggplot2
#'
#' @importFrom dplyr desc select case_when lag mutate group_by filter summarise ungroup
#'               pull distinct n arrange across slice left_join
#' @importFrom ggplot2 ggplot geom_text scale_color_manual xlim ylim facet_wrap labs theme_void theme element_text aes vars
#' @importFrom tidyr pivot_longer
#' @importFrom refugees population
#'
#' @export
#' @examples
#' plot_ctr_keyfig(
#'   year = 2024,
#'   country_asylum_iso3c = "COL"
#' )
plot_ctr_keyfig <- function(year = 2021, 
                            country_asylum_iso3c) {
  
  # Get country name
  country_name_text <- refugees::population |>
    dplyr::filter(coa_iso == country_asylum_iso3c) |>
    dplyr::slice(1) |>
    dplyr::pull(coa_name)
  
  # Calculate Total POC for current year
  total_poc <- refugees::population |>
    dplyr::filter(
      year == !!year,
      coa_iso == country_asylum_iso3c
    ) |>
    dplyr::summarise(total = sum(refugees, asylum_seekers, idps, oip, stateless, ooc, hst, na.rm = TRUE)) |>
    dplyr::pull()
  
  # Calculate Total POC for previous year
  total_poc_prev <- refugees::population |>
    dplyr::filter(
      year == (!!year - 1),
      coa_iso == country_asylum_iso3c
    ) |>
    dplyr::summarise(total = sum(refugees, asylum_seekers, idps, oip, stateless, ooc, hst, na.rm = TRUE)) |>
    dplyr::pull()
  
  # Calculate percentage change
  perc_change_poc <- (total_poc - total_poc_prev) / total_poc_prev * 100
  
  # Prepare data for plotting
  keyfig <- refugees::population |>
    dplyr::filter(
      year == !!year,
      coa_iso == country_asylum_iso3c
    ) |>
    tidyr::pivot_longer(
      cols = c(refugees, asylum_seekers, idps, oip, stateless, ooc, hst),
      names_to = "population_type",
      values_to = "value"
    ) |>
    dplyr::group_by(population_type) |>
    dplyr::summarise(value = sum(value, na.rm = TRUE)) |>
    dplyr::mutate(
      population_type_label = dplyr::case_when(
        population_type == "refugees" ~ "REF",
        population_type == "asylum_seekers" ~ "ASY",
        population_type == "idps" ~ "IDP",
        population_type == "oip" ~ "OIP",
        population_type == "stateless" ~ "STA",
        population_type == "ooc" ~ "OOC",
        population_type == "hst" ~ "HST",
        TRUE ~ "Other"
      )
    ) |>
    dplyr::filter(value > 0) |>
    dplyr::mutate(
      icon = "\uf0c0", # Unicode for FontAwesome icon
      label = paste0(format(round(value, 0), big.mark = ","), " ", population_type_label),
      pal = population_type_label,
      fig = population_type_label
    )
  
  # Plotting
  p <- ggplot2::ggplot(keyfig) +
    # LAYER 1: ICONS (Switched to geom_text)
    ggplot2::geom_text(
      ggplot2::aes(
        x = 0.5,       # Centered horizontally in the facet
        y = 1.8,       # Positioned in upper half
        label = icon,
        color = pal
      ),
      family = "Font Awesome 6 Solid", # Ensure this font is loaded via sysfonts/showtext
      size = 10        # Adjusted size for geom_text (unit is mm, not pt)
    ) +
    # LAYER 2: LABELS (Switched to geom_text)
    ggplot2::geom_text(
      ggplot2::aes(
        x = 0.5,       # Centered horizontally
        y = 0.8,       # Positioned below icon
        label = label,
        color = pal
      ),
      family = "Lato", # Ensure Lato is loaded
      size = 5,        # Adjusted size
      fontface = "bold"
    ) +
    ggplot2::scale_color_manual(values = c(
      "IDP" = "#00B398",
      "OIP" = "#EF4A60",
      "ASY" = "#18375F",
      "REF" = "#0072BC",
      "OOC" = "#8395b9",
      "STA" = "#E1CC0D"
    )) +
    ggplot2::xlim(c(0, 1)) + # Normalized limits 0-1 for easier centering
    ggplot2::ylim(c(0, 3)) +
    ggplot2::facet_wrap(ggplot2::vars(fig), ncol = 2) +
    ggplot2::labs(
      title = paste0("Key Figures for ", country_name_text, " as of ", year),
      subtitle = paste0(
        "A total of ",
        format(round(total_poc, 0), scientific = FALSE, big.mark = ","),
        " people, ",
        ifelse(perc_change_poc > 0, "increasing", "decreasing"),
        " by ", round(abs(perc_change_poc), 1),
        "% compared to the previous year"
      ),
      caption = "Source: UNHCR.org refugee-statistics"
    ) +
    ggplot2::theme_void() +
    ggplot2::theme(
      strip.text = ggplot2::element_blank(), # Hide strip text as the icon/label explains it
      legend.position = "none",
      plot.title = ggplot2::element_text(family = "Lato", face = "bold", size = 18, hjust = 0.5),
      plot.subtitle = ggplot2::element_text(family = "Lato", size = 12, hjust = 0.5, margin = ggplot2::margin(b = 20))
    )
  
  return(p)
}
