# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

#' Main country of origin - Absolute value
#'
#' @param year Numeric value of the year (for instance 2020)
#' @param country_asylum_iso3c Character value with the ISO-3 character code of the Country of Asylum
#' @param top_n_countries Numeric value of number of main countries that the graph should display
#' @param pop_type Character value. Possible population type (e.g.: REF, IDP, ASY,   OIP, OOC, STA)
#' 
#' @importFrom ggplot2  ggplot  aes  coord_flip   element_blank element_line
#'             element_text expansion geom_bar geom_col geom_hline unit stat_summary
#'             geom_label geom_text labs  position_stack  scale_color_manual scale_colour_manual 
#'             geom_text
#'             scale_fill_manual scale_x_continuous scale_x_discrete  scale_y_continuous   sym theme  
#' @importFrom utils  head
#' @importFrom tidyselect where
#' @importFrom stringr  str_replace 
#' @importFrom scales cut_short_scale label_percent label_number breaks_pretty
#' @importFrom stats  reorder aggregate 
#' @importFrom dplyr  desc select  case_when lag mutate group_by filter summarise ungroup
#'               pull distinct n arrange across slice left_join
#' @importFrom tidyr pivot_longer
#' @importFrom unhcrthemes theme_unhcr
#' 
#' @return a ggplot2 object
#' 
#' @export
#'

#' @examples
#' plot_ctr_population_type_abs(year = 2020,
#'                     country_asylum_iso3c = "USA",
#'                     top_n_countries = 4,
#'                     pop_type = "REF",
#'                     show_diff_label = FALSE
#'                     ) 
#' 
#' ## Same with 9 top countries and asylum seekers included
#' plot_ctr_population_type_abs(year = 2020,
#'                     country_asylum_iso3c = "USA",
#'                     top_n_countries = 9,
#'                     pop_type = "ASY",
#'                     show_diff_label = TRUE
#'                     ) 
#' 
plot_ctr_population_type_abs <- function(year = 2021,
                                         country_asylum_iso3c = country_asylum_iso3c,
                                         top_n_countries = 9,
                                         pop_type = "REF",
                                         show_diff_label = TRUE
) {
  
  
  
  cols_poptype <- list(ASY = c("Asylum seekers", "#18375F"),
                       REF = c("Refugees", "#0072BC"),
                       #VDA = c("Venezuelans Displaced Abroad", "#EF4A60"), 
                       OIP = c("Other people in need of international protection", "#EF4A60"), 
                       OOC = c("Others of Concern to UNHCR", "#999999"),
                       IDP = c("Internally displaced persons", "#00B398"),
                       STA = c("Stateless Persons", "#E1CC0D")
  )
  
  
  df <- 
    unhcrdatapackage::end_year_population_totals  |> 
    filter(CountryAsylumCode != "UKN",
           !is.na(CountryAsylumCode),
           (Year == year | Year == year -1),  #### Parameter
           CountryAsylumCode == country_asylum_iso3c, #### Parameter
    )  |>  
    select(Year, CountryAsylumName, CountryOriginName,!!sym(pop_type)) |>
    group_by(Year, CountryAsylumName, CountryOriginName) |>
    filter(!!sym(pop_type) != 0) |>
    mutate(pop_type_value = sum(!!sym(pop_type), na.rm=TRUE)) |> 
    ungroup() |>
    group_by(CountryAsylumName, CountryOriginName) |> 
    arrange(Year) |>
    mutate(diff_pop_type_value = label_percent(accuracy = 0.1,
                                                trim = FALSE) (((pop_type_value-lag(pop_type_value))/lag(pop_type_value)))  ) |> 
    ungroup() |>
    filter(Year == year) |> 
    mutate(
      origin_data_prot = forcats::fct_lump_n(
        f = CountryOriginName,
        n = top_n_countries,  #### Parameter
        w = pop_type_value,
        other_level = 'Other nationalities',
        ties.method = "last"
      )
    ) |>
    mutate(origin_data_prot = forcats::fct_explicit_na(origin_data_prot,
                                                       'Other nationalities'),
           diff_pop_type_value = case_when(origin_data_prot == 'Other nationalities' ~ "",
                                           TRUE ~ diff_pop_type_value)) |>
    group_by(CountryAsylumName, diff_pop_type_value, origin_data_prot) |>
    summarise(pop_type_value = sum(pop_type_value, na.rm = TRUE)) |>
    ungroup() |> 
    arrange(desc(pop_type_value)) |>
    filter(pop_type_value != 0L) |>
    mutate(
      origin_data_prot = forcats::fct_rev(forcats::fct_inorder(origin_data_prot)),
      origin_data_prot =  suppressWarnings(
        case_when(
          origin_data_prot == "Other nationalities" ~ forcats::fct_relevel(origin_data_prot,
                                                                           "Other nationalities",
                                                                           after = 0),
          TRUE ~ origin_data_prot
        )
      ),
      perc = label_percent(
        accuracy = 1,
        trim = TRUE
      )(  pop_type_value / sum(pop_type_value))
    )
  
  CountryAsylum_name_text <- df |> 
    distinct(CountryAsylumName) |> 
    pull()
  
  
  p <- ggplot() +
    geom_col(data = df, 
             aes(x = pop_type_value, y = origin_data_prot),
             fill = cols_poptype[[pop_type]][2],
             width = 0.8) +
    ## Position label differently in the bar in white - outside bar in black
    geom_text(
      data = subset(df, pop_type_value < max(pop_type_value) / 1.5),
      aes(
        x = pop_type_value,
        y = origin_data_prot,
        label = label_number(accuracy = 1,
                             scale_cut = cut_short_scale())(pop_type_value)
      ),
      hjust = -0.1 ,
      vjust = 0.5,
      colour = "black",
      size = 6
    ) +
    geom_text(
      data = subset(df, pop_type_value >= max(pop_type_value) / 1.5),
      aes(
        x = pop_type_value,
        y = origin_data_prot,
        label = label_number(accuracy = 1,
                             scale_cut = cut_short_scale())(pop_type_value)),
      hjust = 1.1 ,
      vjust = 0.5,
      colour = "white",
      size = 6
    ) 
  
  # Add diff labels
  if(show_diff_label == TRUE) {
    # diff label positive general
    p <- p + geom_text( 
      data = subset(df, with(df, grepl('^[0-9]', diff_pop_type_value)) & (pop_type_value < max(pop_type_value) / 1.5)),
      aes(
        x = pop_type_value,
        y = origin_data_prot,
        label = paste(intToUtf8(9650), diff_pop_type_value)
      ),
      hjust = -1.2,
      vjust = 0.5,
      colour = "grey",
      size = 5
    ) +
    # diff label negative general
    geom_text(
      data = subset(df, with(df, grepl('-', diff_pop_type_value)) & (pop_type_value < max(pop_type_value) / 1.5)),
      aes(
        x = pop_type_value,
        y = origin_data_prot,
        label = paste(intToUtf8(9660), diff_pop_type_value)
      ),
      hjust = -1.2,
      vjust = 0.5,
      colour = "#0472bc",
      size = 5
    ) +
  # diff label positive max
    geom_text(
      data = subset(df, with(df, grepl('^[0-9]', diff_pop_type_value)) & (pop_type_value >= max(pop_type_value) / 1.5)),
      aes(
        x = pop_type_value,
        y = origin_data_prot,
        label = paste(intToUtf8(9650), diff_pop_type_value)
      ),
      hjust = -0.4,
      vjust = 0.5,
      colour = "grey",
      size = 5
    ) +
  # diff label negative max
    geom_text(
      data = subset(df, with(df, grepl('-', diff_pop_type_value)) & (pop_type_value >= max(pop_type_value) / 1.5)),
      aes(
        x = pop_type_value,
        y = origin_data_prot,
        label = paste(intToUtf8(9660), diff_pop_type_value)
      ),
      hjust = -0.4,
      vjust = 0.5,
      colour = "#0472bc",
      size = 5
    )} 
  p <- p + 
    labs(title = paste0(CountryAsylum_name_text, ": ", cols_poptype[[pop_type]][1], " | ",  year),
         subtitle = paste0("Top ",  top_n_countries, " Countries of Origin"),
         x = "Number of People",
         caption = "Source: UNHCR.org/refugee-statistics") +
    scale_x_continuous(expand = expansion(c(0, 0.1))) +
    theme_unhcr(grid = FALSE, axis = "y", 
                axis_title = FALSE, axis_text = "y",
                font_size = 14) +
    theme(legend.direction = "vertical",
          legend.key.size = unit(0.8, 'cm'),
          text = element_text(size = 20),
          plot.subtitle=element_text(size=19),
          plot.title = element_text(size=23),
          plot.caption = element_text(size=13))
  
  return(p) 
}
