# WARNING - Generated by {fusen} from dev/dev_plot_Region.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot Regional Treemap
#'
#' @param year Numeric value of the year (for instance 2020)
#' @param region Character value including the UNHCR region
#' @param pop_type Vector of character values. Possible population type (e.g.: REF, IDP, ASY, OIP, OIP, OOC, STA)
#' @param label_font_size Numeric value for label font size
#' @import treemapify
#' @export
#' @examples
#' plot_reg_treemap(
#'     year = 2024,
#'     region = "The Americas",
#'     label_font_size = 15
#' )
plot_reg_treemap <- function(year = 2024,
                             region = "The Americas",
                             pop_type = c("REF", "ASY", "IDP", "OIP", "OOC", "STA"),
                             label_font_size = 15) {
    datatree_pre <- refugees::population |>
        dplyr::filter(year == !!year) |>
        dplyr::mutate(unhcr_region = countrycode::countrycode(coa_iso, "iso3c", "unhcr.region", warn = FALSE)) |>
        dplyr::filter(unhcr_region == region)

    if (nrow(datatree_pre) == 0) {
        p <- ggplot2::ggplot() +
            ggplot2::annotate("text", x = 1, y = 1, size = 12, label = paste0("No records for ", region, " in ", year)) +
            ggplot2::theme_void()
        return(p)
    }

    datatree <- datatree_pre |>
        tidyr::pivot_longer(
            cols = c(refugees, asylum_seekers, idps, oip, stateless, ooc, hst),
            names_to = "population_type",
            values_to = "value"
        ) |>
        dplyr::mutate(population_type_label = dplyr::case_when(
            population_type == "refugees" ~ "REF",
            population_type == "asylum_seekers" ~ "ASY",
            population_type == "idps" ~ "IDP",
            population_type == "oip" ~ "OIP",
            population_type == "stateless" ~ "STA",
            population_type == "ooc" ~ "OOC",
            population_type == "hst" ~ "HCO",
            TRUE ~ "Other"
        )) |>
        dplyr::mutate(population_type_name = dplyr::case_when(
            population_type == "refugees" ~ "Refugees",
            population_type == "asylum_seekers" ~ "Asylum-seekers",
            population_type == "idps" ~ "Internally displaced persons",
            population_type == "oip" ~ "Other people in need of international protection",
            population_type == "stateless" ~ "Stateless people",
            population_type == "ooc" ~ "Others of concern to UNHCR",
            population_type == "hst" ~ "Host community",
            TRUE ~ "Other"
        )) |>
        dplyr::filter(population_type_label %in% pop_type) |>
        dplyr::group_by(year, unhcr_region, population_type_label, population_type_name) |>
        dplyr::summarise(value = sum(value, na.rm = TRUE), .groups = "drop") |>
        dplyr::ungroup() |>
        dplyr::mutate(
            freqinReg = scales::label_percent(accuracy = .1, suffix = "%")(value / sum(value))
        )

    if (nrow(datatree) == 0 || sum(datatree$value) == 0) {
        p <- ggplot2::ggplot() +
            ggplot2::annotate("text", x = 1, y = 1, size = 12, label = paste0("No records for ", region, " in ", year)) +
            ggplot2::theme_void()
        return(p)
    }

    p <- ggplot2::ggplot(
        datatree,
        ggplot2::aes(
            area = value,
            fill = population_type_label,
            label = paste0(freqinReg, "\n", stringr::str_wrap(population_type_name, 20))
        )
    ) +
        treemapify::geom_treemap() +
        treemapify::geom_treemap_text(
            colour = "white",
            place = "centre", size = label_font_size,
            family = "Lato"
        ) +
        ggplot2::scale_fill_manual(values = cols_poptype_abbr) +
        unhcrthemes::theme_unhcr(font_size = 14) +
        ggplot2::theme(legend.position = "none") +
        ggplot2::labs(
            title = paste0("Population of Concern & Affected Host Communities in ", region),
            subtitle = paste0("As of ", year, ", a total of ", format(round(sum(datatree$value), -3), big.mark = ","), " Individuals"),
            x = "",
            y = "",
            caption = "Source: UNHCR.org/refugee-statistics"
        )

    return(p)
}
