# WARNING - Generated by {fusen} from dev/dev_plot_Country.Rmd: do not edit by hand # nolint: line_length_linter.

#' Graph of Population Type Over year
#'
#' @param year Numeric value of the year (for instance 2020)
#' @param lag Number of year to used as comparison base
#' @param country_asylum_iso3c Character value with the ISO-3 character code of the Country of Asylum
#' @param pop_type Vector of character values. Possible population type
#'                  (e.g.: REF, IDP, ASY, OIP, OIP, OOC, STA)
#'
#' @import ggplot2
#' @importFrom utils  head
#' @importFrom tidyselect where
#' @importFrom stringr  str_replace
#' @importFrom scales cut_short_scale label_percent label_number breaks_pretty
#' @importFrom stats  reorder aggregate
#' @importFrom dplyr  desc select  case_when lag mutate group_by filter summarise ungroup
#'               pull distinct n arrange across slice left_join
#' @importFrom tidyr pivot_longer
#' @importFrom unhcrthemes theme_unhcr
#'
#' @return a ggplot2 object
#'
#' @export
#'
#'
#' @examples
#' p <- plot_ctr_population_type_per_year(
#'   year = 2018,
#'   country_asylum_iso3c = "BRA",
#'   lag = 5,
#'   pop_type = c(
#'     "REF",
#'     "ASY",
#'     "OIP",
#'     "OOC",
#'     "STA",
#'     "IDP"
#'   )
#' )
#' p
#' ## Raw data can always be accessed with
#' # knitr::kable(ggplot2::ggplot_build(p)$plot$data )

plot_ctr_population_type_per_year <- function(year = 2024,
                                              lag = 5,
                                              country_asylum_iso3c,
                                              pop_type = c("REF", "ASY", "IDP", "OIP", "STA", "OOC")) {
  dict_pop_type_name <- c(
    "refugees" = "Refugees",
    "returned_refugees" = "Returned refugees",
    "asylum_seekers" = "Asylum-seekers",
    "idps" = "Internally displaced persons",
    "returned_idps" = "Returned idps",
    "oip" = "Other people in need of international protection",
    "stateless" = "Stateless people",
    "ooc" = "Others of concern to UNHCR",
    "hst" = "Host community"
  )

  dict_pop_type_label <- c(
    "refugees" = "REF",
    "returned_refugees" = "RETURNED_REF",
    "asylum_seekers" = "ASY",
    "idps" = "IDP",
    "returned_idps" = "RETURNED_IDP",
    "oip" = "OIP",
    "stateless" = "STA",
    "ooc" = "OOC",
    "hst" = "HST"
  )

  cols_poptype <- c(
    "Asylum-seekers" = "#18375F",
    "Refugees" = "#0072BC",
    # "Venezuelans Displaced Abroad" = "#EF4A60",
    "Other people in need of international protection" = "#EF4A60",
    "Others of Concern to UNHCR" = "#999999",
    "Internally displaced persons" = "#00B398",
    "Stateless Persons" = "#E1CC0D"
  )


  df <- refugees::population |>
    dplyr::filter(
      year >= (!!year - lag) & year <= !!year, #### Parameter
      coa_iso == country_asylum_iso3c, #### Parameter
    ) |>
    tidyr::pivot_longer(
      cols = c(refugees, asylum_seekers, idps, oip, stateless, ooc, hst),
      names_to = "population_type",
      values_to = "value"
    ) |>
    dplyr::mutate(
      population_type_label = stringr::str_replace_all(population_type, pattern = dict_pop_type_label)
    ) |>
    dplyr::filter(
      population_type_label %in% pop_type #### Parameter
    ) |>
    dplyr::group_by(year, coa_name, population_type, population_type_label) |>
    dplyr::summarise(dplyr::across(tidyselect::where(is.numeric), ~ sum(.x, na.rm = TRUE)), .groups = "drop") |>
    dplyr::mutate(
      population_type_name = stringr::str_replace_all(population_type, pattern = dict_pop_type_name)
    )


  ## need to sort with so that the small value are on the top for better legibility
  # levels(as.factor(df$population_type_label)) is alpha...
  # let's sort based on value from this year
  df$population_type_name <- factor(df$population_type_name,
    levels = unique(df$population_type_name[order(df$value)])
  )


  country_name_text <- df |>
    dplyr::distinct(coa_name) |>
    dplyr::pull()

  year_breaks <- diff(range(df$year)) + 1

  p <- ggplot2::ggplot() +
    ggplot2::geom_col(
      data = df,
      ggplot2::aes(
        x = year,
        y = value,
        fill = population_type_name
      ),
      width = 0.7
    ) +

    ## Need some conditions to put labels or not o the chart - to avoid cluttered
    # chart..

    ggplot2::geom_text(
      data = df |> dplyr::filter(value > mean(df$value) * 0.1),
      ggplot2::aes(
        x = year,
        y = value,
        color = population_type_name,
        label = scales::label_number(
          accuracy = .1,
          scale_cut = scales::cut_short_scale()
        )(value)
      ),
      position = ggplot2::position_stack(vjust = 0.5),
      show.legend = FALSE,
      size = 5
    ) +
    ## This add the total on the top of the chart..
    ggplot2::stat_summary(
      data = df,
      fun = sum,
      ggplot2::aes(
        x = year,
        y = value,
        label = scales::label_number(
          accuracy = .1,
          scale_cut = scales::cut_short_scale()
        )(ggplot2::after_stat(y)),
        group = year
      ),
      geom = "text", size = 5, vjust = -0.5
    ) +
    ggplot2::scale_color_manual(values = c(
      "#FFFFFF",
      "#FFFFFF",
      "#FFFFFF",
      "#FFFFFF",
      "#FFFFFF",
      "#FFFFFF"
    )) +
    ggplot2::scale_fill_manual(
      values = cols_poptype,
      drop = TRUE,
      limits = force
    ) +
    ggplot2::scale_x_continuous(breaks = scales::breaks_pretty(n = year_breaks)) +
    ggplot2::scale_y_continuous(expand = ggplot2::expansion(c(0, 0.1))) +
    ggplot2::labs(
      title = paste0(country_name_text, ": Population Type per year"),
      subtitle = "Number of people (thousand)",
      caption = "Source: UNHCR.org/refugee-statistics"
    ) +
    unhcrthemes::theme_unhcr(
      grid = FALSE, axis = "x",
      axis_title = FALSE, axis_text = "x",
      font_size = 14
    ) +
    ggplot2::theme(
      legend.direction = "horizontal",
      legend.position = "bottom",
      legend.text = ggplot2::element_text(size = ggplot2::rel(0.5)),
      legend.key.size = ggplot2::unit(0.8, "cm"),
      text = ggplot2::element_text(size = 20)
    )

  return(p) # print(p)
}
