# WARNING - Generated by {fusen} from dev/dev_plot_Region.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot Regional Map
#'
#' @param year Numeric value of the year (for instance 2020)
#' @param region Character value including the UNHCR region
#' @param topn Numeric value for number of top items
#' @param pop_type Vector of character values. Possible population type
#' @param projection Character value for map projection
#' @param maxSymbolsize Numeric value for maximum symbol size
#' @export
#' @examples
#' plot_reg_map(
#'     year = 2024,
#'     region = "The Americas"
#' )
plot_reg_map <- function(year = 2024,
                         region = "The Americas",
                         topn = 5,
                         pop_type = c("REF", "ASY", "OIP"),
                         projection = "Mercator",
                         maxSymbolsize = .25) {
    # Check if package is installed
    if (!requireNamespace("rnaturalearth", quietly = TRUE)) {
        stop("Package 'rnaturalearth' is needed for this function to work. Please install it.", call. = FALSE)
    }

    # 1. Prepare Data
    data <- refugees::population |>
        dplyr::filter(year == !!year) |>
        dplyr::mutate(unhcr_region = countrycode::countrycode(coa_iso, "iso3c", "unhcr.region")) |>
        dplyr::filter(unhcr_region == region) |>
        tidyr::pivot_longer(
            cols = c(refugees, asylum_seekers, idps, oip, stateless, ooc, hst),
            names_to = "population_type",
            values_to = "value"
        ) |>
        dplyr::mutate(population_type_label = dplyr::case_when(
            population_type == "refugees" ~ "REF",
            population_type == "asylum_seekers" ~ "ASY",
            population_type == "idps" ~ "IDP",
            population_type == "oip" ~ "OIP",
            population_type == "stateless" ~ "STA",
            population_type == "ooc" ~ "OOC",
            population_type == "hst" ~ "HCO",
            TRUE ~ "Other"
        )) |>
        dplyr::filter(population_type_label %in% pop_type) |>
        dplyr::group_by(coa_iso, coa_name) |>
        dplyr::summarise(value = sum(value, na.rm = TRUE), .groups = "drop")

    # 2. Get World Map (sf)
    world_sf <- rnaturalearth::ne_countries(scale = "medium", returnclass = "sf") |>
        dplyr::filter(iso_a3 != "ATA") |> # Exclude Antarctica
        dplyr::mutate(unhcr_region = countrycode::countrycode(iso_a3, "iso3c", "unhcr.region")) |>
        sf::st_make_valid()

    # Filter map to region if standard projection limits are needed,
    # but for "logic of plot_ctr_location" which usually shows global or relevant context,
    # we might want to show the whole region + context or just clip to region.
    # plot_reg_map usually shows the specific region.
    region_sf <- world_sf |>
        dplyr::filter(unhcr_region == region)

    # 3. Join Data
    map_data <- region_sf |>
        dplyr::left_join(data, by = c("iso_a3" = "coa_iso"))

    # 4. Plot
    p <- ggplot2::ggplot() +
        ggplot2::geom_sf(
            data = region_sf,
            fill = "#e6e6e6",
            color = "white",
            linewidth = 0.1
        ) +
        ggplot2::geom_sf(
            data = map_data,
            ggplot2::aes(fill = value),
            color = "white",
            linewidth = 0.1
        ) +
        ggplot2::coord_sf(datum = NA) +
        ggplot2::labs(
            title = paste0("Forced Displacement in ", region),
            subtitle = paste0("Number of people (", paste(pop_type, collapse = ", "), ") as of ", year),
            caption = "Source: UNHCR.org/refugee-statistics",
            x = NULL, y = NULL
        ) +
        unhcrthemes::scale_fill_unhcr_c(
            palette = "pal_blue",
            name = NULL,
            labels = scales::label_number(scale_cut = scales::cut_short_scale()),
            na.value = "#e6e6e6"
        ) +
        unhcrthemes::theme_unhcr(
            font_size = 14,
            grid = FALSE,
            axis = FALSE
        ) +
        ggplot2::theme(
            legend.key.width = ggplot2::unit(2, "cm"),
            legend.position = "top",
            legend.justification = "left",
            legend.title.align = 0,
            axis.text = ggplot2::element_blank(),
            axis.title = ggplot2::element_blank(),
            panel.grid = ggplot2::element_blank()
        )

    return(p)
}
