# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

#' Main country of origin - Percentage
#'
#' @param year Numeric value of the year (eg.: 2020)
#' @param country_asylum_iso3c Character value with the ISO-3 character code of the Country of Asylum
#' @param top_n_countries Numeric value of number of main countries that the graph should display
#' @param pop_type Character value. Possible population type (e.g.: REF, IDP, ASY, VDA, OOC, STA)
#' 
#' @return
#' Main country of origin - Percentage Graph
#' @export
#'

#' @examples
#' 
#' plot_ctr_population_type_perc(year = 2021,
#'                     country_asylum_iso3c = "BRA",
#'                     top_n_countries = 9,
#'                     pop_type = "REF"  ) 
plot_ctr_population_type_perc <- function(year = 2021,
                                country_asylum_iso3c = country_asylum_iso3c,
                                top_n_countries = 9,
                                pop_type = "REF"
                              ) {
    require(ggplot2)
  require(tidyverse)
  cols_poptype <- list(ASY = c("Asylum-seekers", "#18375F"),
                       REF = c("Refugees", "#0072BC"),
                       VDA = c("Venezuelans Displaced Abroad", "#EF4A60"), 
                       OOC = c("Others of Concern to UNHCR", "#999999"),
                       IDP = c("Internally Displaced Persons", "#00B398"),
                       STA = c("Stateless Persons", "#E1CC0D")
  )
  
  
  df <-  
    unhcrdatapackage::end_year_population_totals  |> 
    dplyr::filter(CountryAsylumCode != "UKN",
                  !is.na(CountryAsylumCode),
                  Year == year,  #### Parameter
                  CountryAsylumCode == country_asylum_iso3c, #### Parameter
    )  |>  
    dplyr::select(CountryAsylumName, CountryOriginName,!!sym(pop_type)) |>
    dplyr::group_by(CountryAsylumName, CountryOriginName) |>
    dplyr::filter(!!sym(pop_type) != 0) |>
    dplyr::mutate(pop_type_value = sum(!!sym(pop_type), na.rm=TRUE)) |> 
    dplyr::ungroup() |>
    dplyr::mutate(
      origin_data_prot = forcats::fct_lump_n(
        f = CountryOriginName,
        n = top_n_countries,  #### Parameter
        w = pop_type_value,
        other_level = 'Other nationalities',
        ties.method = "last"
      )
    ) |>
    dplyr::mutate(origin_data_prot = forcats::fct_explicit_na(origin_data_prot,
                                                              'Other nationalities')) |>
    dplyr::group_by(CountryAsylumName,origin_data_prot) |>
    dplyr::summarise(pop_type_value = sum(pop_type_value, na.rm = TRUE)) |>
    dplyr::ungroup() |> 
    dplyr::arrange(desc(pop_type_value)) |>
    dplyr::filter(pop_type_value != 0L) |>
    dplyr::mutate(
      origin_data_prot = forcats::fct_rev(forcats::fct_inorder(origin_data_prot)),
      origin_data_prot =  suppressWarnings(
        dplyr::case_when(
          origin_data_prot == "Other nationalities" ~ forcats::fct_relevel(origin_data_prot,
                                                                           "Other nationalities",
                                                                           after = 0),
          TRUE ~ origin_data_prot
        )
      ),
      perc = scales::percent(
        pop_type_value / sum(pop_type_value),
        accuracy = 1,
        trim = FALSE
      )
    )
  
  CountryAsylum_name_text <- df |> 
    dplyr::distinct(CountryAsylumName) |> 
    dplyr::pull()



p <- 
  ggplot(df) +
  geom_col(aes(x = pop_type_value, y = origin_data_prot),
           fill = cols_poptype[[pop_type]][2],
           width = 0.8) +
  ## Position label differently in the bar in white - outside bar in black
  geom_text(
    data = subset(df, pop_type_value < max(pop_type_value) / 1.5),
    aes(
      x = pop_type_value,
      y = origin_data_prot,
      label = perc
    ),
    hjust = -0.1 ,
    vjust = 0.5,
    colour = "black",
    size = 5
  ) +
  geom_text(
    data = subset(df, pop_type_value >= max(pop_type_value) / 1.5),
    aes(
      x = pop_type_value,
      y = origin_data_prot,
      label = perc
    ),
    hjust = 1.1 ,
    vjust = 0.5,
    colour = "white",
    size = 5
  ) +
  labs(title = paste0(CountryAsylum_name_text, ": Main Countries of origin (", cols_poptype[[pop_type]][1], ")", " | ",  year),
       subtitle = "Percentage",
       caption = "Source: UNHCR Refugee Data Finder\n© UNHCR, The UN Refugee Agency") +
  scale_x_continuous(expand = expansion(c(0, 0.1))) +
 # unhcrthemes::theme_unhcr(grid = FALSE, axis = "y", axis_title = FALSE, axis_text = "y") +
  theme(legend.direction = "vertical",
        legend.key.size = unit(0.8, 'cm'),
        text = element_text(size = 20),
        plot.subtitle=element_text(size=19),
        plot.title = element_text(size=23),
        plot.caption = element_text(size=13))
  print(p)
  }
