# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

#' Graph of population type per year
#'
#' @param start_year Numeric value of first year  
#' @param country_asylum_iso3c Character value with the ISO-3 character code of the Country of Asylum
#' @param pop_type Vector of character values. Possible population type (e.g.: REF, IDP, ASY, OIP, OIP, OOC, STA)
#'
#' @export
#'
#'

#' @examples
#' 
#' plot_ctr_population_type_per_year(start_year = 2016,
#'                          country_asylum_iso3c = "PAN",
#'                           pop_type = c("REF", 
#'                                        "ASY", 
#'                                        #"VDA", 
#'                                        "OIP", 
#'                                        "OOC",
#'                                        "STA",
#'                                        "IDP" )
#'                   )
plot_ctr_population_type_per_year <- function(start_year = 2015,
                                     country_asylum_iso3c = country_asylum_iso3c,
                                     pop_type = Population.type
                                     ) {
  
  require(ggplot2)
  require(tidyverse)
  require(scales)
  cols_poptype <- c("Asylum-seekers" = "#18375F",
                    "Refugees" = "#0072BC",
                    #"Venezuelans Displaced Abroad" = "#EF4A60", 
                    "Other people in need of international protection" = "#EF4A60", 
                    "Others of Concern to UNHCR" = "#999999",
                    "Internally Displaced Persons" = "#00B398",
                    "Stateless Persons" = "#E1CC0D")
  
  
  df <- unhcrdatapackage::end_year_population_totals_long  |> 
    dplyr::filter(CountryAsylumCode != "UKN",
                  !is.na(CountryAsylumCode),
                  Year >= start_year,  #### Parameter
                  CountryAsylumCode == country_asylum_iso3c, #### Parameter
                  Population.type %in% pop_type #### Parameter
    )  |>  
    dplyr::group_by(Year, CountryAsylumName, Population.type.label)  |> 
    dplyr::summarise(Value = sum(Value, na.rm = TRUE)) |> 
    dplyr::ungroup()
  
  CountryAsylum_name_text <- df |> 
    dplyr::distinct(CountryAsylumName) |> 
    dplyr::pull()
  
  year_breaks <- diff(range(df$Year)) + 1 
  
  p <- ggplot(df) +
    geom_col(aes(x = Year, y = Value, fill = Population.type.label),
             width = 0.7) +
    geom_text(aes(x = Year, 
                  y = Value, 
                  color = Population.type.label, 
                  label = scales::label_number( accuracy = 1,
                                   scale_cut = scales::cut_short_scale())(Value)),
              position = position_stack(vjust = 0.5),
              show.legend = FALSE,
              size = 5) +
    scale_color_manual(values = c("#FFFFFF",
                                  "#FFFFFF",
                                  "#FFFFFF",
                                  "#FFFFFF",
                                  "#FFFFFF",
                                  "#FFFFFF")) +
    scale_fill_manual(values = cols_poptype,
                      drop = TRUE,
                      limits = force) +
    scale_x_continuous(breaks = scales::pretty_breaks(n = year_breaks)) +
    scale_y_continuous(expand = expansion(c(0, 0.1))) +
    labs(title = paste0(CountryAsylum_name_text, ": Population type per year"), 
         subtitle = "Number of people (thousand)",
         caption = "Source: UNHCR Refugee Data Finder") +
    unhcrthemes::theme_unhcr(grid = FALSE, axis = "x", axis_title = FALSE, axis_text = "x") +
    stat_summary(fun = sum, aes(x = Year, y = Value, label = scales::label_number( accuracy = 1,
                                   scale_cut = scales::cut_short_scale())(..y..), group = Year), 
                 geom = "text", size = 5,
                 vjust = -0.5) +
    theme(legend.direction = "vertical",
          legend.key.size = unit(0.8, 'cm'),
          text = element_text(size = 20),
          plot.subtitle=element_text(size=19),
          plot.title = element_text(size=23),
          plot.caption = element_text(size=13))
  
  return(p) # print(p)
  }
