# WARNING - Generated by {fusen} from /dev/dev_plot_Country.Rmd: do not edit by hand

#' Graph of Population Type Over Year
#'
#' @param year Numeric value of the year (for instance 2020)
#' @param lag Number of year to used as comparison base
#' @param country_asylum_iso3c Character value with the ISO-3 character code of the Country of Asylum
#' @param pop_type Vector of character values. Possible population type 
#'                  (e.g.: REF, IDP, ASY, OIP, OIP, OOC, STA)
#' 
#' @import ggplot2              
#' @importFrom utils  head
#' @importFrom tidyselect where
#' @importFrom stringr  str_replace 
#' @importFrom scales cut_short_scale label_percent label_number breaks_pretty
#' @importFrom stats  reorder aggregate 
#' @importFrom dplyr  desc select  case_when lag mutate group_by filter summarise ungroup
#'               pull distinct n arrange across slice left_join
#' @importFrom tidyr pivot_longer
#' @importFrom unhcrthemes theme_unhcr
#' 
#' @return a ggplot2 object
#'
#' @export
#'
#'

#' @examples
#' 
#' p <- plot_ctr_population_type_per_year(
#'                          year = 2022,
#'                          country_asylum_iso3c = "PAN",
#'                          lag = 5,
#'                          pop_type = c("REF", 
#'                                        "ASY", 
#'                                        "OIP", 
#'                                        "OOC",
#'                                        "STA",
#'                                        "IDP" )
#'                   )
#' p
#' ## Raw data can always be accessed with 
#' #knitr::kable(ggplot2::ggplot_build(p)$plot$data )
plot_ctr_population_type_per_year <- function(year = 2022,
                                              lag = 5, 
                                     country_asylum_iso3c = country_asylum_iso3c,
                                     pop_type = Population.type
                                     ) {
  



  cols_poptype <- c("Asylum seekers" = "#18375F",
                    "Refugees" = "#0072BC",
                    #"Venezuelans Displaced Abroad" = "#EF4A60", 
                    "Other people in need of international protection" = "#EF4A60", 
                    "Others of Concern to UNHCR" = "#999999",
                    "Internally displaced persons" = "#00B398",
                    "Stateless Persons" = "#E1CC0D")
  
  
  df <- ForcedDisplacementStat::end_year_population_totals_long  |> 
    filter(CountryAsylumCode != "UKN",
                  !is.na(CountryAsylumCode),
                  Year >= (year - lag),  #### Parameter
                  CountryAsylumCode == country_asylum_iso3c, #### Parameter
                  Population.type %in% pop_type #### Parameter
    )  |>  
    group_by(Year, CountryAsylumName, Population.type.label)  |> 
    summarise(Value = sum(Value, na.rm = TRUE)) |> 
    ungroup()
  
  ## need to sort with so that the small value are on the top for better legibility 
  # levels(as.factor(df$Population.type.label)) is alpha... 
  # let's sort based on value from this year
  df$Population.type.label <- factor(df$Population.type.label,
          levels =  unique(df$Population.type.label[order(df$Value)])
                                     )
  
  
  
  CountryAsylum_name_text <- df |> 
    distinct(CountryAsylumName) |> 
    pull()
  
  year_breaks <- diff(range(df$Year)) + 1 
  
  p <- ggplot() +
    geom_col( data = df, 
             aes(x = Year, 
                 y = Value, 
                 fill = Population.type.label),
             width = 0.7) +
    
    ## Need some conditions to put labels or not o the chart - to avoid cluttered
    # chart.. 
    
    geom_text(data = df |> filter(Value > mean(df$Value) *0.1), 
             aes(x = Year, 
                  y = Value, 
                  color = Population.type.label, 
                  label = label_number(accuracy = .1,
                                   scale_cut = cut_short_scale())(Value)),
              position = position_stack(vjust = 0.5),
              show.legend = FALSE,
              size = 5) +
    ## This add the total on the top of the chart..
    stat_summary(data = df, 
                  fun = sum, 
                 aes(x = Year,
                     y = Value, 
                     label = scales::label_number(accuracy = .1,
                                          scale_cut = cut_short_scale())(after_stat(y)),
                     group = Year), 
                 geom = "text", size = 5,    vjust = -0.5) +
    scale_color_manual(values = c("#FFFFFF",
                                  "#FFFFFF",
                                  "#FFFFFF",
                                  "#FFFFFF",
                                  "#FFFFFF",
                                  "#FFFFFF")) +
    scale_fill_manual(values = cols_poptype,
                      drop = TRUE,
                      limits = force) +
    scale_x_continuous(breaks = scales::breaks_pretty(n = year_breaks)) +
    scale_y_continuous(expand = expansion(c(0, 0.1))) +
    labs(title = paste0(CountryAsylum_name_text, ": Population Type per Year"), 
         subtitle = "Number of people (thousand)",
         caption = "Source: UNHCR.org/refugee-statistics") +
    theme_unhcr(grid = FALSE, axis = "x", 
                axis_title = FALSE, axis_text = "x",
              font_size = 14) +
    
    theme(legend.direction = "horizontal",
          legend.position = "bottom",
          legend.text=element_text(size = rel(0.5)),
          legend.key.size = unit(0.8, 'cm'),
          text = element_text(size = 20),
          plot.subtitle=element_text(size=19),
          plot.title = element_text(size=23),
          plot.caption = element_text(size=13))
  
  return(p) # print(p)
  }

 


