# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

#' Population Pyramid
#'
#' @param year Numeric value of the year (for instance 2020)
#' @param country_asylum_iso3c Character value with the ISO-3 character code of the Country of Asylum
#' @param pop_type Vector of character values. Possible population type (e.g.: REF, IDP, ASY, OIP, OOC, STA)
#' 
#' @export
#'

#' @examples
#' # 
#' plot_ctr_pyramid(year = 2021,
#'                             country_asylum_iso3c = "VEN",
#'                             pop_type = c("REF", "ASY")
#'          )
#' 
plot_ctr_pyramid <- function(year = 2021,
                     country_asylum_iso3c = country_asylum_iso3c,
                     pop_type = pop_type) {
  require(ggplot2)
  require(tidyverse)
  require(scales)
  
  demographics1 <- unhcrdatapackage::demographics |>
                   dplyr::left_join( unhcrdatapackage::reference |> 
                                       select(UNHCRBureau, iso_3),  
                                     by = c("CountryAsylumCode" = "iso_3")) |> 
                   dplyr::filter(CountryAsylumCode  == country_asylum_iso3c &
                               Year == year-1 &
                               Population.type  %in% as.vector(pop_type) ) |>
    
                    dplyr::mutate ( totGen = FemaleTotal +MaleTotal,
                               totbreak = Female04 + Female511 + Female1217 + 
                                          Female1859 + Female60ormore + FemaleUnknown +
                                          Male04 + Male511 + Male1217 + Male1859 +
                                          Male60ormore + MaleUnknown,
                               
                               hasbreak = ifelse(Total - totGen == 0, "yes", "no" ))



if( nrow(demographics1) ==  0 ){
  cat(paste0("There's no recorded Gender disaggregation for Forcibly Displaced People across Borders in ",country_asylum_iso3c  ))
  
} else {

  tot <- format( sum(demographics1$Total) ,  big.mark=",")
  totprop <-   format( round( sum(demographics1$totGen) / 
      sum(demographics1$Total )  *100,1),  big.mark=",")  
  
  if (totprop == 0 ) {
    cat(paste0("There's no recorded Gender disaggregation for all of the ",tot, " persons in", country_asylum_iso3c  ))
    
  } else {
    #names(demographics)
    pyramid <-  demographics1[ demographics1$Year == max(demographics1$Year),
                              c(
                                  "Female04",
                                  "Female511",
                                  "Female1217",
                                  "Female1859",
                                  "Female60ormore",
                                  "FemaleUnknown",
                                 # "FemaleTotal",
                                  "Male04",
                                  "Male511",
                                  "Male1217",
                                  "Male1859",
                                  "Male60ormore",
                                  "MaleUnknown"#,
                                 # "MaleTotal"       
                                 )]  
    
    pyramid2 <- data.frame(lapply(pyramid, function(x) { as.numeric( gsub("NA", "0", x)) })) |>
      pivot_longer(
        cols = Female04:MaleUnknown,
        names_to = "Class",
        values_to = "Sum",
        values_drop_na = TRUE
      ) 
    
    pyramid3 <- as.data.frame(aggregate(pyramid2$Sum,
                                              by = list(pyramid2$Class#, pyramid2$REGION_UN
                                                        ),
                                              sum))
    names(pyramid3)[1] <- "Class"
    names(pyramid3)[2] <- "Count"
    
    pyramid3 <- pyramid3 |> 
      mutate(gender = case_when(str_detect(Class, "Male") ~ "Male",
                                str_detect(Class, "Female") ~ "Female")) |> 
      mutate(age = case_when(str_detect(Class, "04") ~ "0-4",
                             str_detect(Class, "511") ~ "5-11",
                             str_detect(Class, "1217") ~ "12-17",
                             str_detect(Class, "1859") ~ "18-59",
                             str_detect(Class, "60") ~ "60+",
                             str_detect(Class, "Unknown") ~ "Unknown")) 
    
    pyramid3$pc <- pyramid3$Count / sum(pyramid3$Count) * 100
    pyramid3$age <- factor(pyramid3$age, levels = c("0-4", "5-11",  "12-17",  "18-59", "60+", "Unknown"))
    
    pyramidplot <- ggplot(pyramid3, aes(x = age, 
                         fill = gender,
                          y = ifelse(test = gender == "Female",
                                yes = -pc, no = pc)) ) + 
      geom_bar(stat = "identity") +
      geom_label(aes(x = age,
                     y = ifelse(test = gender == "Female",
                                yes = -pc -5 , no = pc),
                    label =  paste0(format(round(pc, 1),  big.mark=","),"%") 
                    ),
                 hjust = 0,
                 vjust = 0.5,
                 colour = "black",
                 fill = NA,
                 label.size = NA,
                # family = "Lato",
                 size = 4) +
      scale_y_continuous(labels = abs, limits = max(pyramid3$pc) * c(-1,1)) +
      labs(title = paste0("Population Pyramid for Forcibly Displaced People" ),
           
           subtitle = paste0("As of ", year, 
                             ", gender disaggregation is available for ", totprop, " % of the ",tot,
                             " individuals in", country_asylum_iso3c),
           x = "", 
           y = "Percent of population",
           caption =  "Data: UNHCR Refugee Population Statistics Database; Visualisation: UnhcrDataPackage.\n Forced Displacement includes Refugees, Asylym Seekers and Venezuelan Displaced Abroad Population Groups.") +
      scale_colour_manual(values = c("#126db4","#01ab91"), # based on Asia Report
                          aesthetics = c("colour", "fill")) +
      coord_flip()+
     #  unhcRstyle::unhcr_theme(base_size = 12) +
       theme(panel.grid.major.x = element_line(color = "#cbcbcb"), 
                panel.grid.major.y = element_blank())
    
    print(pyramidplot)
 }
 }
}
