# WARNING - Generated by {fusen} from dev/dev_plot_Country.Rmd: do not edit by hand # nolint: line_length_linter.

#' Increases and Decreases in Population Groups
#'
#' @param year Numeric value of the year (for instance 2020)
#' @param country_asylum_iso3c Character value with the ISO-3 character code of the Country of Asylum
#' @param pop_type Vector of character values. Possible population type (e.g.: REF, IDP, ASY, OIP, OOC, STA)
#'
#' @importFrom ggplot2  ggplot  aes  coord_flip   element_blank element_line
#'             element_text expansion geom_bar geom_col geom_hline unit stat_summary
#'             geom_label geom_text labs  position_stack  scale_color_manual scale_colour_manual
#'             geom_text
#'             scale_fill_manual scale_x_continuous scale_x_discrete  scale_y_continuous   sym theme
#' @importFrom utils  head
#' @importFrom tidyselect where
#' @importFrom stringr  str_replace
#' @importFrom scales cut_short_scale label_percent label_number breaks_pretty
#' @importFrom stats  reorder aggregate
#' @importFrom dplyr  desc select  case_when lag mutate group_by filter summarise ungroup
#'               pull distinct n arrange across slice left_join
#' @importFrom tidyr pivot_longer  gather separate spread
#' @importFrom unhcrthemes theme_unhcr
#'
#' @return a ggplot2 object
#'
#' @export
#'
#' @examples
#' #
#' plot_ctr_diff_in_pop_groups(
#'   year = 2024,
#'   country_asylum_iso3c = "ROU",
#'   pop_type = c("REF", "ASY")
#' )

plot_ctr_diff_in_pop_groups <- function(year = 2021,
                                        country_asylum_iso3c = country_asylum_iso3c,
                                        pop_type = pop_type) {
  country_name_text <- refugees::population |>
    dplyr::filter(coa_iso == country_asylum_iso3c) |>
    dplyr::distinct(coa_name) |>
    dplyr::pull() |>
    head(1)

  pop_data <- refugees::population |>
    dplyr::filter(coa_iso == country_asylum_iso3c) |>
    dplyr::filter(year %in% c(year, year - 1)) |>
    tidyr::pivot_longer(
      cols = c(refugees, asylum_seekers, idps, oip, stateless, ooc),
      names_to = "population_type",
      values_to = "value"
    ) |>
    dplyr::mutate(population_type = dplyr::case_when(
      population_type == "refugees" ~ "REF",
      population_type == "asylum_seekers" ~ "ASY",
      population_type == "idps" ~ "IDP",
      population_type == "oip" ~ "OIP",
      population_type == "stateless" ~ "STA",
      population_type == "ooc" ~ "OOC",
      TRUE ~ population_type
    )) |>
    dplyr::group_by(year, population_type) |>
    dplyr::summarise(value = sum(value, na.rm = TRUE)) |>
    dplyr::ungroup()

  df <- pop_data |>
    tidyr::pivot_wider(names_from = year, values_from = value, names_prefix = "year_") |>
    dplyr::mutate(
      diffabs = .data[[paste0("year_", year)]] - .data[[paste0("year_", year - 1)]],
      diffper = (.data[[paste0("year_", year)]] - .data[[paste0("year_", year - 1)]]) / .data[[paste0("year_", year - 1)]]
    ) |>
    dplyr::mutate(diffper = scales::label_percent(accuracy = 1, trim = FALSE)(diffper)) |>
    dplyr::filter(population_type %in% pop_type)

  p <- ggplot() +
    geom_col(
      data = df,
      aes(
        x = population_type,
        y = diffabs,
        fill = population_type
      ),
      width = 0.8
    ) +
    scale_fill_manual(
      values = c(
        "ASY" = "#18375F",
        "REF" = "#0072BC",
        "OIP" = "#EF4A60",
        # "VDA" = "#EF4A60",
        "OOC" = "#999999",
        "IDP" = "#00B398",
        "STA" = "#E1CC0D"
      ),
      drop = TRUE, limits = force, guide = "none"
    ) +
    scale_x_discrete(
      labels = c(
        "ASY" = "Asylum-seekers",
        "REF" = "Refugees",
        # "VDA" = "Venezuelans Displaced\nAbroad", ,
        "OIP" = "Other people in need\n of international protection",
        "OOC" = "Others of Concern\nto UNHCR",
        "IDP" = "Internally Displaced\nPersons",
        "STA" = "Stateless Persons"
      ),
      drop = TRUE,
      limits = force
    ) +

    ## Adding labels with conditionned positions...

    geom_text(
      data = subset(df, diffabs >= 0 & diffabs < max(diffabs) / 1.5),
      aes(
        x = population_type,
        y = diffabs,
        label = label_number(
          accuracy = 1,
          scale_cut = cut_short_scale()
        )(diffabs)
      ),
      vjust = -0.5, colour = "black", size = 5
    ) +
    geom_text(
      data = subset(df, diffabs >= 0 & diffabs < max(diffabs) / 1.5),
      aes(
        x = population_type,
        y = diffabs,
        label = paste(intToUtf8(9650), diffper)
      ),
      vjust = -2.0, colour = "black", size = 5
    ) +
    geom_text(
      data = subset(df, diffabs >= 0 & diffabs >= max(diffabs) / 1.5),
      aes(
        x = population_type,
        y = diffabs,
        label = label_number(
          accuracy = 1,
          scale_cut = cut_short_scale()
        )(diffabs)
      ),
      vjust = 2.7, colour = "white", size = 5
    ) +
    geom_text(
      data = subset(df, diffabs >= 0 & diffabs >= max(diffabs) / 1.5),
      aes(
        x = population_type,
        y = diffabs,
        label = paste(intToUtf8(9650), diffper)
      ),
      vjust = 1.2, colour = "white", size = 5
    ) +
    geom_text(
      data = subset(df, diffabs < 0 / 1.5),
      aes(
        x = population_type,
        y = diffabs,
        label = label_number(
          accuracy = 1,
          scale_cut = cut_short_scale()
        )(diffabs)
      ),
      vjust = 1.2, colour = "black", size = 5
    ) +
    geom_text(
      data = subset(df, diffabs < 0 / 1.5),
      aes(
        x = population_type,
        y = diffabs,
        label = paste(intToUtf8(9660), diffper)
      ),
      vjust = 2.7, colour = "black", size = 5
    ) +
    geom_hline(yintercept = 0, color = "black") +
    labs(
      title = paste0(
        country_name_text,
        ": Increases and Decreases in Population Groups | ",
        year - 1,
        "-",
        year
      ),
      subtitle = "Number of people and percentage",
      caption = "Source: UNHCR.org/refugee-statistics"
    ) +
    theme_unhcr(
      grid = FALSE, axis = "x",
      axis_title = FALSE, axis_text = "x",
      font_size = 14
    ) +
    theme(
      axis.line.x = element_line(color = "white"),
      axis.text.x = element_text(size = 10)
    )

  # geom_text(
  #   data = subset(df, diffabs < 0 & diffabs <= min(diffabs) / 1.5),
  #   aes(
  #     x = population_type,
  #     y = diffabs,
  #     label = label_number(accuracy = 1,
  #                                  scale_cut = cut_short_scale())(diffabs)
  #   ),
  #   vjust = -2.0 ,
  #   colour = "white",
  #   size = 5
  # )  +
  #   geom_text(
  #     data = subset(df, diffabs < 0 & diffabs <= min(diffabs) / 1.5),
  #     aes(
  #       x = population_type,
  #       y = diffabs,
  #       label = diffper
  #     ),
  #     vjust = -0.5 ,
  #     colour = "white",
  #     size = 5
  #   ) +


  return(p) # print(p)
}
