# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

#' Plotting ration Refugee/Asylum seekers vs Migrant within a country
#'
#' @param year Numeric value of the year (for instance 2020)
#' @param country_asylum_iso3c Character value with the ISO-3 character code of the Country of Asylum
#' @param pop_type Vector of character values. Possible population type (e.g.: REF, IDP, ASY, OIP, OOC, STA)
#' 
#' @importFrom ggplot2  ggplot  aes  coord_flip   element_blank element_line
#'             element_text expansion geom_bar geom_col geom_hline unit stat_summary
#'             geom_label geom_text labs  position_stack  scale_color_manual scale_colour_manual 
#'             geom_text geom_point scale_size coord_cartesian
#'             scale_fill_manual scale_x_continuous scale_x_discrete  scale_y_continuous   sym theme  
#' @importFrom utils  head
#' @importFrom tidyselect where
#' @importFrom stringr  str_replace 
#' @importFrom scales cut_short_scale percent label_number breaks_pretty
#' @importFrom stats  reorder aggregate 
#' @importFrom wbstats  wb 
#' @importFrom dplyr  desc select  case_when lag mutate group_by filter summarise ungroup
#'               pull distinct n arrange across slice left_join
#' @importFrom tidyr pivot_longer
#' @importFrom unhcrthemes theme_unhcr
#' @importFrom viridis scale_fill_viridis
#' 
#' @export
#'
#' @examples
#' plot_ctr_disp_migrant(year = 2021,
#'                     country_asylum_iso3c = "BRA",
#'                   pop_type = c("REF", "ASY", "OIP") )
plot_ctr_disp_migrant <- function(year = 2021,
                              country_asylum_iso3c = country_asylum_iso3c,
                              pop_type = pop_type){
  
  wb_data <- wbstats::wb( indicator = c("SP.POP.TOTL", "NY.GDP.MKTP.CD", "NY.GDP.PCAP.CD", "NY.GNP.PCAP.CD"),
             
               country = c( country_asylum_iso3c )  ,         
               startdate = 1990, 
               enddate = 2020, 
               return_wide = TRUE)
      # Renaming variables for further matching
      names(wb_data)[1] <- "iso_3"
      names(wb_data)[2] <- "Year"
      wb_data$Year <- as.numeric(wb_data$Year)

  
  displaced <- left_join( x= unhcrdatapackage::end_year_population_totals_long, 
                               y= unhcrdatapackage::reference, 
                               by = c("CountryAsylumCode" = "iso_3")) %>%
              filter(Population.type  %in% pop_type) %>%
              filter(CountryAsylumCode == country_asylum_iso3c) %>%
              filter( Year == year ) %>%
              mutate( iso_3 = CountryOriginCode) %>% 
              group_by(Year, iso_3,CountryOriginName, UNHCRBureau, hcr_subregion, INCOME_GRP) %>%
              summarise(Asylum_Refugee_in = sum(Value) )  %>%
              filter( iso_3 != "UKN") %>%
              arrange( desc(Asylum_Refugee_in)) %>%
              head(10)%>%
              as.data.frame()
  
  thiscode <- unhcrdatapackage::reference |>
                filter(iso_3 == country_asylum_iso3c) |>
                 select(M49_code) |>
                 pull()

  migrant <-  left_join( x= unhcrdatapackage::migrants, 
                               y= unhcrdatapackage::reference, 
                               by = c("CountryOriginM49" = "M49_code")) %>%
              filter(CountryDestinationM49 == thiscode) %>%
              group_by(Year, iso_3,CountryOriginName, UNHCRBureau, hcr_subregion, INCOME_GRP) %>%
              summarise(Immigrant = sum(Value) ) %>%
              mutate( shareOrgin = (Immigrant / sum(Immigrant))*100 ) %>%
              filter( Year == 2020 ) %>%
              as.data.frame() %>%
              mutate( Year = as.numeric(Year) ) %>%
              mutate( shareOrgin =  round(Immigrant / sum(Immigrant),3)*100 )

#str(migrant)
#str(displaced)

thismigProfile <-  migrant  %>%
  dplyr::full_join( displaced[ ,c("Asylum_Refugee_in","iso_3" )], by = c("iso_3")) %>%
  dplyr::left_join(  wb_data, by = c("Year","iso_3")) %>%
  ## Calculate a few ration
  mutate( ratioAsylum_Refugee_in = (Asylum_Refugee_in / SP.POP.TOTL)*100,
          ratioImmigrant = (Immigrant / SP.POP.TOTL)*100,
          ratioAsylum_Immigrant = (Asylum_Refugee_in / Immigrant)*100)  %>%
  arrange( desc(Asylum_Refugee_in)) %>%
  head(10)


if( nrow(displaced) ==  0 ){
  p <- paste0("There's no recorded Forcibly Displaced Poeple across Borders in ",thiscountry )
  
} else {

p <- ggplot(thismigProfile,
       aes(x= ratioAsylum_Immigrant, 
           y= shareOrgin, 
           size= Asylum_Refugee_in, 
           fill= INCOME_GRP,
           label = iso_3)) +
  geom_point(alpha=0.5, 
             shape=21, 
             color="black") +
  scale_size(range = c(.1, 24), guide= "none", ## Do not show Legend
             name="# of Forcibly Displaced People") +
  viridis::scale_fill_viridis(discrete=TRUE,
                              name="Country Income Classification") +
  # facet_wrap( vars(Year ), ncol = 2) +
  coord_cartesian(clip = "off") +
  ggrepel::geom_label_repel(box.padding = 0.5,
                            size =4,
                            # max.overlaps = 2 
                            fill = "white", 
                            xlim = c(-Inf, Inf), 
                            ylim = c(-Inf, Inf)) + 
  labs(title = "Share of Forcibly Displaced People within Migrants",
       subtitle = "Per Country of Origin as of 2020. \n The size of the circle represents the number of Refugees & Asylum Seekers ", 
       x = "Ratio Asylum / Immigrant",
       y ="Ratio Country / Total Immigrant",
       caption = "UNDESA Migrant Stock & UNHCR (includes REF +ASY+OIP in calculation) as of 2020.\n Only countries with more than 50K Forcibly Displaced Accorss borders are presented.") +
  theme_unhcr(font_size = 12)  + ## Insert UNHCR Style
  theme(legend.position="bottom", 
        panel.grid.major.y  = element_line(color = "#cbcbcb"), 
        panel.grid.major.x  = element_line(color = "#cbcbcb"), 
        panel.grid.minor = element_blank())   ### changing grid line that should appear
  
}

return(p)
    
}
