# WARNING - Generated by {fusen} from dev/dev_plot_Region.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot Regional Decrease
#'
#' @param year Numeric value of the year (for instance 2020)
#' @param lag Number of year to used as comparison base
#' @param topn Numeric value for number of top countries to show
#' @param region Character value including the UNHCR region
#' @param pop_type Vector of character values. Possible population type
#' @param category_font_size Numeric value for axis text font size
#' @export
#' @examples
#' plot_reg_decrease(
#'     year = 2024,
#'     region = "The Americas",
#'     category_font_size = 10
#' )
plot_reg_decrease <- function(year = 2024,
                              lag = 5,
                              topn = 5,
                              region = "The Americas",
                              pop_type = c("REF", "ASY", "OIP"),
                              category_font_size = 10) {
    thisyear <- year
    baseline <- thisyear - lag
    data <- refugees::population |>
        dplyr::filter(year == baseline | year == thisyear) |>
        dplyr::mutate(unhcr_region = countrycode::countrycode(coa_iso, "iso3c", "unhcr.region")) |>
        dplyr::filter(unhcr_region == region) |>
        tidyr::pivot_longer(
            cols = c(refugees, asylum_seekers, idps, oip, stateless, ooc, hst),
            names_to = "population_type",
            values_to = "value"
        ) |>
        dplyr::mutate(population_type_label = dplyr::case_when(
            population_type == "refugees" ~ "REF",
            population_type == "asylum_seekers" ~ "ASY",
            population_type == "idps" ~ "IDP",
            population_type == "oip" ~ "OIP",
            population_type == "stateless" ~ "STA",
            population_type == "ooc" ~ "OOC",
            population_type == "hst" ~ "HCO",
            TRUE ~ "Other"
        )) |>
        dplyr::filter(population_type_label %in% pop_type) |>
        dplyr::mutate(year = dplyr::case_when(
            year == thisyear ~ paste("thisyear"),
            year == baseline ~ paste("baseline")
        )) |>
        dplyr::group_by(coa_name, year) |>
        dplyr::summarise(value = sum(value, na.rm = TRUE), .groups = "drop") |>
        dplyr::select(coa_name, year, value) |>
        dplyr::mutate(
            coa_name = stringr::str_replace(coa_name, " \\(Bolivarian Republic of\\)", ""),
            coa_name = stringr::str_replace(coa_name, "Iran \\(Islamic Republic of\\)", "Iran"),
            coa_name = stringr::str_replace(coa_name, "United Kingdom of Great Britain and Northern Ireland", "UK")
        ) |>
        tidyr::spread(year, value) |>
        dplyr::mutate(gap = baseline - thisyear) |>
        dplyr::arrange(dplyr::desc(gap)) |>
        utils::head(topn) |>
        tidyr::gather(
            key = year,
            value = value,
            -coa_name,
            -gap
        ) |>
        dplyr::mutate(year = dplyr::case_when(
            year == "thisyear" ~ paste(thisyear),
            year == "baseline" ~ paste(baseline)
        ))

    p <- ggplot2::ggplot(
        data,
        ggplot2::aes(
            x = stats::reorder(coa_name, gap),
            y = value,
            fill = as.factor(year)
        )
    ) +
        ggplot2::coord_flip() +
        ggplot2::geom_bar(stat = "identity", position = "dodge") +
        ggplot2::geom_hline(yintercept = 0, linewidth = 1, colour = "#333333") +
        ggplot2::scale_fill_manual(values = c("#0072bc", "#FAAB18")) +
        ggplot2::labs(
            title = "Biggest Decrease of Population",
            subtitle = paste0(
                topn, " Biggest change in Refugee Population, ",
                region, " ", baseline, " - ", thisyear
            ),
            x = "", y = "",
            caption = "Source: UNHCR.org/refugee-statistics"
        ) +
        ggplot2::scale_y_continuous(labels = scales::label_number(
            accuracy = 1,
            scale_cut = scales::cut_short_scale()
        )) +
        unhcrthemes::theme_unhcr(font_size = 14) +
        ggplot2::theme(
            panel.grid.major.x = ggplot2::element_line(color = "#cbcbcb"),
            panel.grid.major.y = ggplot2::element_blank(),
            axis.text.y = ggplot2::element_text(size = category_font_size)
        )

    return(p)
}
