# WARNING - Generated by {fusen} from dev/dev_plot_Region.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot Regional RSD
#'
#' @param year Numeric value of the year (for instance 2020)
#' @param region Character value including the UNHCR region
#' @param top_n_countries Numeric value for number of top countries to show
#' @param measure Character value for the measure to display
#' @param category_font_size Numeric value for axis text font size
#' @import patchwork
#' @export
#' @examples
#' plot_reg_rsd(
#'     year = 2024,
#'     region = "The Americas",
#'     measure = "Recognized",
#'     category_font_size = 10
#' )
plot_reg_rsd <- function(year = 2024,
                         region,
                         top_n_countries = 10,
                         measure = "Recognized",
                         category_font_size = 10) {
    measurelabel <- dplyr::case_when(
        measure == "Recognized" ~ "Recognized Refugee Status Decisions",
        measure == "ComplementaryProtection" ~ "Complementary Protection Decisions",
        measure == "TotalDecided" ~ "Total Decision (independently of the outcome)",
        measure == "RefugeeRecognitionRate" ~ "Refugee Recognition Rate",
        measure == "TotalRecognitionRate" ~ "Total Recognition Rate",
        TRUE ~ measure
    )

    data <- refugees::asylum_decisions |>
        dplyr::filter(year == !!year) |>
        dplyr::mutate(unhcr_region = countrycode::countrycode(coa_iso, "iso3c", "unhcr.region")) |>
        dplyr::filter(unhcr_region == region) |>
        dplyr::mutate(DecisionsAveragePersonsPerCase = 1)

    topOrigin <- data |>
        dplyr::rename(CountryOriginName = coo_name) |>
        dplyr::group_by(CountryOriginName) |>
        dplyr::summarize(
            Recognized = sum(dec_recognized, na.rm = TRUE),
            ComplementaryProtection = sum(dec_other, na.rm = TRUE),
            TotalDecided = sum(dec_total, na.rm = TRUE)
        ) |>
        dplyr::mutate(
            RefugeeRecognitionRate = (Recognized) / TotalDecided,
            TotalRecognitionRate = (Recognized + ComplementaryProtection) / TotalDecided
        ) |>
        dplyr::mutate(CountryOriginName = stringr::str_replace(CountryOriginName, " \\(Bolivarian Republic of\\)", ""))

    topOrigin1 <- topOrigin |>
        dplyr::mutate(measured = .data[[measure]]) |>
        dplyr::arrange(dplyr::desc(measured)) |>
        utils::head(top_n_countries)

    topasyl <- data |>
        dplyr::rename(CountryAsylumName = coa_name) |>
        dplyr::group_by(CountryAsylumName) |>
        dplyr::summarize(
            Recognized = sum(dec_recognized, na.rm = TRUE),
            ComplementaryProtection = sum(dec_other, na.rm = TRUE),
            TotalDecided = sum(dec_total, na.rm = TRUE)
        ) |>
        dplyr::mutate(
            RefugeeRecognitionRate = (Recognized) / TotalDecided,
            TotalRecognitionRate = (Recognized + ComplementaryProtection) / TotalDecided
        )

    topasyl1 <- topasyl |>
        dplyr::mutate(measured = .data[[measure]]) |>
        dplyr::arrange(dplyr::desc(measured)) |>
        utils::head(top_n_countries)

    rsdasyl <- ggplot2::ggplot(topasyl1, ggplot2::aes(
        y = measured,
        x = stats::reorder(CountryAsylumName, measured)
    )) +
        ggplot2::scale_y_continuous(labels = ifelse(measure %in% c("RefugeeRecognitionRate", "TotalRecognitionRate"),
            scales::label_percent(accuracy = 0, suffix = "%"),
            scales::label_number(accuracy = 1, scale_cut = scales::cut_short_scale())
        )) +
        ggplot2::geom_bar(stat = "identity", fill = "#0072bc") +
        ggplot2::coord_flip() +
        ggplot2::labs(
            subtitle = paste0("For top ", top_n_countries, " Countries of Asylum"),
            x = " ",
            y = " "
        ) +
        unhcrthemes::theme_unhcr(
            grid = "Y",
            axis = "x", axis_title = "",
            font_size = category_font_size
        ) +
        ggplot2::theme(
            panel.grid.major.x = ggplot2::element_line(color = "#cbcbcb"),
            panel.grid.major.y = ggplot2::element_blank()
        )

    rsdorigin <- ggplot2::ggplot(topOrigin1, ggplot2::aes(
        y = measured,
        x = stats::reorder(CountryOriginName, measured)
    )) +
        ggplot2::scale_y_continuous(labels = ifelse(measure %in% c("RefugeeRecognitionRate", "TotalRecognitionRate"),
            scales::label_percent(accuracy = 0, suffix = "%"),
            scales::label_number(accuracy = 1, scale_cut = scales::cut_short_scale())
        )) +
        ggplot2::geom_bar(stat = "identity", fill = "#0072bc") +
        ggplot2::coord_flip() +
        ggplot2::labs(
            subtitle = paste0("For top ", top_n_countries, " Countries of Origin"),
            x = " ",
            y = " "
        ) +
        unhcrthemes::theme_unhcr(
            grid = "Y",
            axis = "x", axis_title = "",
            font_size = category_font_size
        ) +
        ggplot2::theme(
            panel.grid.major.x = ggplot2::element_line(color = "#cbcbcb"),
            panel.grid.major.y = ggplot2::element_blank()
        )

    patchworkRSDa <- rsdasyl + rsdorigin
    patchworkRSDa1 <- patchworkRSDa +
        ggplot2::theme(legend.position = "none") +
        patchwork::plot_annotation(
            title = paste0(measurelabel, " | ", year, ", in ", region),
            caption = "Source: UNHCR.org/refugee-statistics "
        )

    return(patchworkRSDa1)
}
