# WARNING - Generated by {fusen} from dev/dev_plot_Region.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot Regional Proportion Origin
#'
#' @param year Numeric value of the year (for instance 2020)
#' @param region Character value including the UNHCR region
#' @param label_font_size Numeric value for label font size
#' @param category_font_size Numeric value for axis text font size
#' @export
#' @examples
#' plot_reg_prop_origin(
#'     year = 2024,
#'     region = "The Americas",
#'     label_font_size = 6,
#'     category_font_size = 10
#' )
plot_reg_prop_origin <- function(year = 2024, region = "The Americas", label_font_size = 6, category_font_size = 10) {
    wb_data <- WDI::WDI(
        country = "all",
        indicator = c(
            "SP.POP.TOTL", "NY.GDP.MKTP.CD",
            "NY.GDP.PCAP.CD", "NY.GNP.PCAP.CD"
        ),
        start = year - 1,
        end = year - 1,
        extra = TRUE
    )

    # Rename year to Year to match downstream code expectations
    if ("year" %in% names(wb_data)) {
        wb_data <- wb_data |> dplyr::rename(Year = year)
    }

    departed <- refugees::population |>
        dplyr::filter(year == !!year) |>
        dplyr::mutate(unhcr_region = countrycode::countrycode(coo_iso, "iso3c", "unhcr.region")) |>
        dplyr::filter(unhcr_region == region) |>
        tidyr::pivot_longer(
            cols = c(refugees, asylum_seekers, oip),
            names_to = "population_type",
            values_to = "value"
        ) |>
        dplyr::group_by(coo_name, coo_iso) |>
        dplyr::summarise(value = sum(value, na.rm = TRUE), .groups = "drop") |>
        dplyr::mutate(coo_name = stringr::str_replace(
            coo_name,
            " \\(Bolivarian Republic of\\)", ""
        )) |>
        dplyr::left_join(
            wb_data |>
                dplyr::select("SP.POP.TOTL", "iso3c", "Year") |>
                dplyr::filter(Year == year - 1),
            by = c("coo_iso" = "iso3c")
        ) |>
        dplyr::mutate(ref.part = round(value / (SP.POP.TOTL + value), 4)) |>
        dplyr::arrange(dplyr::desc(ref.part)) |>
        utils::head(10)

    p <- ggplot2::ggplot(
        departed,
        ggplot2::aes(x = ref.part, forcats::fct_reorder(coo_name, ref.part))
    ) +
        ggplot2::geom_col(fill = "#0072BC") +
        ggplot2::geom_label(ggplot2::aes(label = scales::label_percent(accuracy = .1)(ref.part)),
            hjust = 1,
            vjust = 0.5,
            colour = "white",
            fill = NA,
            linewidth = NA,
            family = "Lato",
            size = label_font_size
        ) +
        ggplot2::scale_x_continuous(labels = scales::label_percent(accuracy = .1)) +
        ggplot2::labs(
            x = NULL,
            y = NULL,
            title = stringr::str_wrap(paste0("Number of refugees, asylum seekers & displaced across borders by country of origin in ", region), 60),
            subtitle = stringr::str_wrap("Top 10 Countries, as a proportion of the national population of that country of origin (SDG indicator 10.7.4)", 80),
            caption = stringr::str_wrap("Source: UNHCR.org/refugee-statistics. \n Total count of population who have been recognized as refugees as a proportion of the total population of their country of origin, expressed per 100,000 population. Refugees refers to persons recognized by the Government and/or UNHCR, or those in a refugee-like situation.  Population refers to total resident population in a given country in a given year.", 100)
        ) +
        unhcrthemes::theme_unhcr(
            grid = "X",
            axis = "y",
            axis_title = "x",
            font_size = 14
        ) +
        ggplot2::theme(
            axis.text.y = ggplot2::element_text(size = category_font_size)
        )

    return(p)
}
