# WARNING - Generated by {fusen} from dev/dev_plot_Region.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot Solution over time in the region
#'
#' Description
#' @param year Numeric value of the year (for instance 2020)
#' @param region Character value with the related UNHCR bureau - when left null, it will display the whole world
#' @param lag Number of year to used as comparison base
#' @importFrom ggplot2  ggplot  aes  coord_flip   element_blank element_line
#'             element_text expansion geom_bar geom_col geom_hline unit stat_summary
#'             geom_label geom_text labs  position_stack  scale_color_manual scale_colour_manual
#'             geom_text geom_smooth
#'             scale_fill_manual scale_x_continuous scale_x_discrete  scale_y_continuous   sym theme
#' @importFrom utils  head
#' @importFrom tidyselect where
#' @importFrom stringr  str_replace
#' @importFrom scales cut_short_scale label_percent label_number breaks_pretty
#' @importFrom stats  reorder aggregate
#' @importFrom dplyr  if_else desc select  case_when lag mutate group_by filter summarise ungroup
#'               pull distinct n arrange across slice left_join
#' @importFrom tidyr pivot_longer
#' @importFrom unhcrthemes theme_unhcr
#' @importFrom ggrepel geom_label_repel
#'
#' @return a ggplot2 object
#'
#' @export
#' @export
#' @examples
#' plot_reg_solution(
#'   year = 2024,
#'   region = "The Americas",
#'   lag = 10
#' )
plot_reg_solution <- function(year = 2024,
                              region = "The Americas",
                              lag = 10) {

  solutions_long <- refugees::solutions |>
    dplyr::mutate(unhcr_region = countrycode::countrycode(coa_iso, "iso3c", "unhcr.region")) |>
    dplyr::filter(unhcr_region == region) |>
    tidyr::pivot_longer(
      cols = c(naturalisation, resettlement, returned_refugees),
      names_to = "solution_type",
      values_to = "value"
    ) |>
    dplyr::group_by(year, solution_type) |>
    dplyr::summarise(value = sum(value, na.rm = TRUE), .groups = "drop")

  p <- ggplot2::ggplot(solutions_long, ggplot2::aes(x = year, y = value, colour = solution_type)) +
    ggplot2::geom_line(size = 1) +
    ggplot2::geom_hline(yintercept = 0, size = 1.1, colour = "#333333") +
    ggplot2::scale_y_continuous(labels = scales::label_number(scale_cut = scales::cut_short_scale())) +
    ggplot2::xlim(c(2000, year + 6)) +
    ggplot2::scale_colour_manual(values = c(
      "naturalisation" = "#a6cee3",
      "resettlement" = "#1f78b4",
      "returned_refugees" = "#b2df8a"
    )) +
    ggplot2::geom_label(
      data = solutions_long |> dplyr::filter(year == max(year)),
      ggplot2::aes(
        x = year + .5,
        y = value,
        label = solution_type,
        color = solution_type
      ),
      hjust = 0,
      vjust = 0.5,
      fill = "white",
      label.size = NA,
      family = "Lato",
      size = 4
    ) +
    unhcrthemes::theme_unhcr(
      grid = "Y",
      axis = "x",
      axis_title = "y",
      font_size = 14,
      legend = FALSE
    ) +
    ggplot2::theme(
      panel.grid.major.y = ggplot2::element_line(color = "#cbcbcb"),
      panel.grid.major.x = ggplot2::element_blank(),
      panel.grid.minor = ggplot2::element_blank()
    ) +
    ggplot2::labs(
      title = paste0("Solution for Displacement in ", region),
      subtitle = "Evolution in the past 20 years",
      x = "",
      y = "",
      caption = "Source: UNHCR.org/refugee-statistics"
    )

  return(p)
}
