# WARNING - Generated by {fusen} from dev/dev_plot_Region.Rmd: do not edit by hand # nolint: line_length_linter.

# Note: Keeping mostly same but improving theme if needed

#' Plot Regional Increase
#'
#' @param year Numeric value of the year (for instance 2020)
#' @param lag Number of year to used as comparison base
#' @param topn Numeric value for number of top countries to show
#' @param region Character value including the UNHCR region
#' @param pop_type Vector of character values. Possible population type
#' @param category_font_size Numeric value for axis text font size
#' @export
#' @examples
#' plot_reg_increase(
#'     year = 2024,
#'     region = "The Americas",
#'     category_font_size = 10
#' )
plot_reg_increase <- function(year = 2024,
                              lag = 5,
                              topn = 5,
                              region = "The Americas",
                              pop_type = c("REF", "ASY", "OIP"),
                              category_font_size = 10) {
    pop_type_label_dict <- c(
        "REF" = "Refugees",
        "ASY" = "Asylum-seekers",
        "IDP" = "Internally displaced persons",
        "OIP" = "Other people in need of international protection",
        "STA" = "Stateless people",
        "OOC" = "Others of concern to UNHCR",
        "HST" = "Host community"
    )

    thisyear <- year
    baseline <- thisyear - lag

    col_this_year <- paste0("year_", thisyear)
    col_baseline <- paste0("year_", baseline)

    data_pivot <- refugees::population |>
        dplyr::filter(year == baseline | year == thisyear) |>
        dplyr::mutate(unhcr_region = countrycode::countrycode(coa_iso, "iso3c", "unhcr.region")) |>
        dplyr::filter(unhcr_region == region) |>
        tidyr::pivot_longer(
            cols = c(refugees, asylum_seekers, idps, oip, stateless, ooc, hst),
            names_to = "population_type",
            values_to = "value"
        ) |>
        dplyr::mutate(population_type_label = dplyr::case_when(
            population_type == "refugees" ~ "REF",
            population_type == "asylum_seekers" ~ "ASY",
            population_type == "idps" ~ "IDP",
            population_type == "oip" ~ "OIP",
            population_type == "stateless" ~ "STA",
            population_type == "ooc" ~ "OOC",
            population_type == "hst" ~ "HCO",
            TRUE ~ "Other"
        )) |>
        dplyr::filter(population_type_label %in% pop_type) |>
        dplyr::group_by(coa_name, year) |>
        dplyr::summarise(value = sum(value, na.rm = TRUE), .groups = "drop") |>
        dplyr::mutate(
            coa_name = stringr::str_replace(coa_name, "Democratic Republic of the Congo", "DRC")
        ) |>
        dplyr::mutate(year_col = paste0("year_", year)) |>
        tidyr::pivot_wider(names_from = year_col, values_from = value, values_fill = NA)

    required_cols <- c("coa_name", col_this_year, col_baseline)

    data <- data_pivot |>
        dplyr::select(tidyselect::any_of(required_cols)) |>
        dplyr::mutate(
            !!col_this_year := dplyr::coalesce(dplyr::if_any(tidyselect::all_of(col_this_year), .default = NA, ~.), 0),
            !!col_baseline := dplyr::coalesce(dplyr::if_any(tidyselect::all_of(col_baseline), .default = NA, ~.), 0)
        ) |>
        dplyr::mutate(gap = .data[[col_this_year]] - .data[[col_baseline]]) |>
        dplyr::arrange(dplyr::desc(gap)) |>
        utils::head(topn)

    if (nrow(data) == 0) {
        message(paste("No increase data found for", region, "between", baseline, "and", thisyear))
        return(invisible(NULL))
    }

    aes_x_baseline <- paste0("year_", baseline)
    aes_x_thisyear <- paste0("year_", thisyear)

    p <- ggplot2::ggplot(
        data,
        ggplot2::aes(
            x = .data[[aes_x_baseline]],
            xend = .data[[aes_x_thisyear]],
            y = stats::reorder(coa_name, gap),
            group = coa_name
        )
    ) +
        ggplot2::geom_segment(
            ggplot2::aes(
                x = .data[[aes_x_baseline]],
                xend = .data[[aes_x_thisyear]],
                y = stats::reorder(coa_name, gap),
                yend = stats::reorder(coa_name, gap)
            ),
            colour = "#dddddd",
            linewidth = 3
        ) +
        ggplot2::geom_point(
            ggplot2::aes(x = .data[[aes_x_baseline]], y = stats::reorder(coa_name, gap)),
            colour = "#0072bc",
            size = 3
        ) +
        ggplot2::geom_point(
            ggplot2::aes(x = .data[[aes_x_thisyear]], y = stats::reorder(coa_name, gap)),
            colour = "#FAAB18",
            size = 3
        ) +
        ggplot2::labs(
            title = paste0("Biggest Increase in Population of Concern (", paste(pop_type_label_dict[pop_type], collapse = ", "), ")"),
            subtitle = paste0("Top ", topn, " Asylum Countries showing the biggest increase, ", baseline, " - ", thisyear),
            x = "Population", y = "",
            caption = "Source: UNHCR.org/refugee-statistics"
        ) +
        ggplot2::scale_x_continuous(labels = scales::label_number(scale_cut = scales::cut_short_scale())) +
        unhcrthemes::theme_unhcr(font_size = 14) +
        ggplot2::theme(
            panel.grid.major.x = ggplot2::element_line(color = "#cbcbcb"),
            panel.grid.major.y = ggplot2::element_blank(),
            axis.text.y = ggplot2::element_text(size = category_font_size)
        )

    return(p)
}
