# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

# usethis::use_rmarkdown_template(
#   template_name = "Country_Factsheet",
#   template_dir = NULL,
#   template_description = "Key Statistical Facts for each Country",
#   template_create_dir = TRUE
# )
#' Generate all country factsheet 
#' 
#' @param year Numeric value of the year (for instance 2022)
#' @param country_asylum_iso3c Character value with the ISO-3 character code of the Country of Asylum
#' @param folder folder within your project where to put the generated report. 
#' Folder will be created if it does not exist
#' 
#' @importFrom unhcrdown paged_simple
#' @importFrom dplyr filter select pull
#' @importFrom rmarkdown render
#' @importFrom here here
#' 
#' @return nothing the file for the report is generated
#' 
#' @export 
#'

#' @examples
#' ## generate for one country
#' # template_CtryFactsheet(year = 2022, country_asylum_iso3c = "USA",   folder = "Report")
#' 
#' ## Generate for a specific region
#' # region <- "Americas"
#' # 
#' # ## get all countries with more than 1000 Reported individuals
#' # ctr <- dplyr::left_join( x= unhcrdatapackage::end_year_population_totals_long, 
#' #                                 y= unhcrdatapackage::reference, 
#' #                                 by = c("CountryAsylumCode" = "iso_3")) %>%
#' #         filter(Year == year & 
#' #                 UNHCRBureau == region ) %>%
#' #         group_by( CountryAsylumName, CountryAsylumCode   ) %>%
#' #         summarise(Value = sum(Value) ) %>%
#' #         ungroup() %>%
#' #         filter( Value  > 1000 )
#' #   
#' #   for ( i in (1:nrow(ctr))) {
#' #     country_asylum_iso3c = ctr[i ,2 ]
#' #     template_CtryFactsheet(year = 2022, country_asylum_iso3c = country_asylum_iso3c,   folder = "Report") 
#' #   }
template_CtryFactsheet <- function(year = 2022,
                                   country_asylum_iso3c,
                                   folder = "Report") {
  
  ## Create the outfolder if it does not exist
  output_dir <- paste0(getwd(),"/",folder)
  if (!dir.exists(output_dir)) {dir.create(output_dir)}
  
  ctrname <- unhcrdatapackage::reference |>
             dplyr::filter( iso_3 == country_asylum_iso3c) |>
             dplyr::select(ctryname) |>
             dplyr::pull()
  
  rmarkdown::render(
    system.file("rmarkdown/templates/country_factsheet/skeleton/skeleton.Rmd", package = "unhcrdatapackage"),
    output_file = here::here(folder, paste0('StatFactsheetCtr-', country_asylum_iso3c, '-', year, '.html') ),
    params = list(countryname= ctrname,
                  country = country_asylum_iso3c, 
                  year = year)  )
}
  

