# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

# usethis::use_rmarkdown_template(
#   template_name = "regional_prez",
#   template_dir = NULL,
#   template_description = "Key Statistical Facts for each Region",
#   template_create_dir = TRUE
# )
#' Generate all country factsheet 
#' 
#' @param year Numeric value of the year (for instance 2020)
#' @param UNHCRBureau Bureau that covers all the countrie factsheet to generate
#' 
#' @importFrom unhcrdown pptx_slides
#' 
#' @export
#'

#' @examples
#' # template_RegPrez(year = 2022, region = "Americas")
template_RegPrez <- function(year = 2022,
                                   region = "Americas") {
  rmarkdown::render(
    system.file("rmarkdown/templates/regional_prez/skeleton/skeleton.Rmd", package = "unhcrdatapackage"),
    output_file = here::here(paste0('StatFactsheet-', ctrcode, '-', year, '.html') ),
    params = list(region=region, 
                  year = year)  )
 
}

