# WARNING - Generated by {fusen} from dev/dev_template.Rmd: do not edit by hand # nolint: line_length_linter.

# usethis::use_rmarkdown_template(
#   template_name = "regional_prez",
#   template_dir = NULL,
#   template_description = "Key Statistical Facts for each Region",
#   template_create_dir = TRUE
# )
#' Generate all country factsheet
#'
#' @param year Numeric value of the year (for instance 2020)
#' @param region Bureau that covers all the countrie factsheet to generate
#' @param lag Number of year to used as comparison base
#'
#' @param folder folder within your project where to put the generated report.
#' Folder will be created if it does not exist
#'
#' @importFrom unhcrdown pptx_slides
#' @importFrom dplyr filter select pull
#' @importFrom rmarkdown render
#' @importFrom here here
#'
#'
#' @return nothing the file for the report is generated
#'
#' @export
#'
#' @examples
#' # template_RegPrez(year = 2024, region = "Americas", lag = 10,   folder = "Report")
#'
#' # # Generate for a specific region
#' # region <- "Americas"
#' # year <- 2024
#' # library(tidyverse)
#' # ## get all countries with more than 1000 Reported individuals
#' # ctr <- refugees::population |>
#' #         filter(year == year &
#' #                 coa_region == region ) |>
#' #         group_by( coa_name, coa_iso   ) |>
#' #         summarise(Value = sum(refugees, asylum_seekers, idps, oip, stateless, others_of_concern, na.rm=TRUE) ) |>
#' #         ungroup() |>
#' #         filter( Value  > 1000 )
#' #
#' #   for ( i in (1:nrow(ctr))) {
#' #     # i <- 1
#' #     country_asylum_iso3c = as.character(ctr[i ,2 ])
#' #     cat(paste0(country_asylum_iso3c, "\n"))
#' #     unhcrviz::template_CtryPrez(year = 2024,
#' #                                   country_asylum_iso3c = country_asylum_iso3c,
#' #                                   folder = "Report")
#' #   }

template_RegPrez <- function(year = 2024,
                             region = "Americas",
                             lag = 10,
                             folder = "Report") {
  ## Create the outfolder if it does not exist
  output_dir <- paste0(getwd(), "/", folder)
  if (!dir.exists(output_dir)) {
    dir.create(output_dir)
  }

  regionname <- dplyr::case_when(
    region == "Americas" ~ "Americas",
    region == "Asia" ~ "Asia & the Pacific",
    region == "EastAfrica" ~ "Eastern Africa",
    region == "Europe" ~ "Europe",
    region == "MENA" ~ "Middle East & North Africa",
    region == "SouthAfrica" ~ "Southern Africa",
    region == "WestAfrica" ~ "Western Africa"
  )
  rmarkdown::render(
    system.file("rmarkdown/templates/regional_prez/skeleton/skeleton.Rmd", package = "unhcrviz"),
    output_file = here::here(folder, paste0("StatFactsheet-", region, "-", year, ".pptx")),
    params = list(
      region = region,
      regionname = regionname,
      year = year,
      lag = lag
    )
  )
}
