# WARNING - Generated by {fusen} from dev/dev_template.Rmd: do not edit by hand # nolint: line_length_linter.

# usethis::use_rmarkdown_template(
#   template_name = "country_slides",
#   template_dir = NULL,
#   template_description = "Slide Deck - Statistical Facts",
#   template_create_dir = TRUE
# )
#' Generate all country factsheet
#'
#' Output is PDF slide deck that preserves well the humanitarian icons
#'
#' @param year Numeric value of the year (for instance 2022)
#' @param country_asylum_iso3c Character value with the ISO-3 character code of the Country
#' @param folder folder within your project where to put the generated report.
#'              Folder will be created if it does not exist
#'
#' @importFrom unhcrdown html_slides
#' @importFrom dplyr filter select pull
#' @importFrom rmarkdown render
#' @importFrom here here
#'
#' @return nothing the file for the report is generated
#'
#' @export
#'
#' @examples
#' ## generate for one country
#' # unhcrviz::template_Ctryslides(year = 2024,
#' #                             country_asylum_iso3c = "CHL",
#' #                             folder = "Report")
#'
#' # ## Generate for a specific region
#' # region <- "Americas"
#' # year <- 2022
#' # library(tidyverse)
#' # ## get all countries with more than 1000 Reported individuals
#' # ctr <- refugees::population |>
#' #         filter(year == year &
#' #                 coa_region == region ) |>
#' #         group_by( coa_name, coa_iso   ) |>
#' #         summarise(Value = sum(refugees, asylum_seekers, idps, oip, stateless, others_of_concern, na.rm=TRUE) ) |>
#' #         ungroup() |>
#' #         filter( Value  > 1000 )
#' #
#' # for ( i in (1:nrow(ctr))) {
#' #     # i <- 1
#' #     country_asylum_iso3ci = as.character(ctr[i ,2 ])
#' #     cat(paste0(country_asylum_iso3ci, "\n"))
#' #     unhcrviz::template_CtryFactsheet(year = 2024,
#' #                                 country_asylum_iso3c = country_asylum_iso3ci,
#' #                                folder = "docs/factsheet")  }

template_Ctryslides <- function(year = 2024,
                                country_asylum_iso3c,
                                folder = "Report") {
  ## Create the outfolder if it does not exist
  output_dir <- paste0(getwd(), "/", folder)
  if (!dir.exists(output_dir)) {
    dir.create(output_dir)
  }

  ctrname <- refugees::population |>
    dplyr::filter(coa_iso == country_asylum_iso3c) |>
    dplyr::distinct(coa_name) |>
    dplyr::pull()

  rmarkdown::render(
    system.file("rmarkdown/templates/country_slides/skeleton/skeleton.Rmd", package = "unhcrviz"),
    output_file = here::here(folder, paste0("StatFactsheet-", country_asylum_iso3c, "-", year, ".html")),
    params = list(
      countryname = ctrname,
      country = country_asylum_iso3c,
      year = year
    )
  )
}
